:toc: 

## 本辞典作成の主旨


　今から十年前、私は上海外国語学院の留学生でした。卒業も間近にひかえた一月三日、中国の友人家族が私の誕生日を祝ってくれました。強い老酒ですっかり酔った私は、友人が送っていくという言葉も振り切って、「大丈夫、大丈夫」と自転車に乗って宿舎へと急ぎました。しかし、一瞬自転車がよろけ、そのまま道路工事中の深い溝に落ち込み、しばらく気を失っていました。ふと気がつくと、私の顔面は額から上唇までぐさりと割れ血だらけになっていました。歩く気力もありませんでした。そこに偶然バスが通りかかりました。バスは止まり、運転手と乗客の二人が私のそばに駆け寄り、抱き抱えながら近くにあった人民解放軍の病院に運んでくれました。応急処置を受けながら、私はその運転手に「お礼をしたいし、名前を教えて欲しい」と言いました。するとその運転手は、「名前？中国人なら誰でもそうする」と笑いながら、名前も言わずに去っていきました。その日を思い出しますと、今も目に涙がにじんできます。
　
　わたしは自分に何ができるのかと、その日以来考えてきました。帰国後日本語教師になったのもそれが理由です。一日本語教師でしかない私にできることと言えば、十年間の教師生活を通して多少とも身につけた日本語教育の経験と知識を形にし、中国の日本語学習者にお届けすることしかありませんでした。しかし、一人ではとてもできない膨大な作業で、何よりも中国語翻訳はとても私にはできないことでした。そんなとき、NIFTY中国論壇フォーラムの16番会議室の仲間や教え子たちが協力に駆けつけてくださいました。この「会話で学ぶ中国人のための日本語表現文型辞典」（中級～上級編）は、日本と在日中国の友人達とが協力して作り上げた共同作品です。またこの辞典が完成するまでには、NIFTY中国論壇フォーラム及びNIFTY日本語フォーラムの日本語教師のみなさん、また出版元桐原ユニ株式会社の有形無形の励ましがありました。この場を借りて心からお礼申し上げます。
　
　思いますに、中国を始めアジアの人々に、深い傷跡を残して終わった侵略戦争から五十余年、まもなく二一世紀の扉をたたこうとしている今日にあってもまだ、日本の政治家や学者達のなかから、みなさんの心を逆撫でするような発言が相次いでいます。しかし、声なき多くの日本人は二度とあのような事態を繰り返してはいけないと心に誓っています。また、繰り返させてはなりません。過去に目を閉ざすもの者には、未来も見えないことでしょう。共に生きるアジア、その未来の追求の中にしか解決の道はありません。
　
　その際大切なことは、コミュニケーションであろうと思います。そしてそれを仲立ちするのは言葉であろうと思います。この辞典が変わらぬ中日友好の架け橋にならんことを祈りつつ、そして、私を助けてくれた運転手や多くの中国友人の手に届くことを祈りつつ、前書きとさせていただきます。

総監：目黒真実

## 001 ＊～間に／＊～間は

名詞　：　　　　　の 　　　　　　　　　　＋ 間(は／が)

動詞　：普通形 （一般動詞は「ている」形） 　　 間に(は)

形容詞：＜イ形：ーい・ーくない＞　　　　　　 間の＋名詞

　　　　＜ナ形：ーな・ーでない＞


♪　会話　♪

李　：先生、長い間ご無沙汰し、誠に申し訳ありませんでした。これはつまらないものですが、・・・。

恩師：ありがとう。せっかくだから遠慮なく。それにしても、しばらく見ない間に、ずいぶんたくましくなったね。

李　：そうですか？日本の企業に勤めていると、何かと鍛えられますし、それに子供も生まれましたから。



♯　解説　♭

　「～間」は期間を表します。動作や状態の継続中を表すので、状態動詞（ある・いる・できる・わかる・要る）を除けば、動詞と接続するときは「ている」形、或いは「ない」形になります。

　問題は「～間」と「～間に」の違いですが、図のように「～間（は／が）」はその期間ずっと継続する動作を、「～間に」はその期間内に完了した動作を表します。作文上の注意点としては、従属節の主語は常に「が」で表しますから、異主語文の中では「Ａが～ている間に、Ｂは～する」の形を取ります。→例題1)2)

　　図あり



§　例文　§

１．私は夏休みの間、都会の喧噪を離れ、ずっとふるさとの実家で過ごした。

２．夏休みの間に、この原稿を書き上げたいと思っている。

３．「若い間の苦労は買ってでもせよ」とよく言われる。

４．私がしばらく留守にしている間に、泥棒が入った。

５．夫婦どちらも元気な間はなんとかなるが、どちらか一方が病気で倒れたりしたら、わが家はお手上げになる。



★　例題　★

1）　鎮痛剤が（効く／効いている）間（に／は）まだよかったが、薬が切れる（時／と）、とたんに虫歯が疼き出した。

2）　私が二年ほど日本（　）留学（する→　　　　　）間（　）、上海の町並みはすっかり変わってしまった。



## 002 ＊～あげく（に）／～果て（に）



名詞：の　　＋　 あげく(に)　　　　　～　　した

動詞：た形 　　　あげくの　＋　名詞

　　　　　　　　 果てに

　　　　　　　　 果ての　　＋　名詞



♪　会話　♪

李　：彼は気の毒だったなあ。さんざん通ったあげくに、先方から電話一本で契約を断られてね。まあ、僕の方もさんざんな目にあったよ。今日は本当についてない。

良子：一体全体、どうしたの？

李　：二時間も並んだあげく、結局、コンサートの切符が手に入らなかったんだ。



♯　解説　♭

　これらの文型は「～した結果～した」を表しますが、後件では常によくない結果の発生を表すところに特徴があります。「～果てに」も同様の意味を表しますが、口語で使われることは多くありません。なお、「あげくの果て」は「あげく」の強調した表現となります。類義文型に「～末に」（→文型116）がありますが、この文型は後件でいい結果も悪い結果も表すことができます。注意すべき点は、これら結果を表す文型は常に文末が完了形「～した」となることです。→例題1)

　悩み抜いた

　　　結果　　　　 ＜客観的表現＞

　　　あげく（に）　＜残念な気持ち＞

　　　末（に）　　　＜色々あったが＞

　帰国することに決めた。



§　例文　§

１．口論のあげく、殴り合いのけんかになった。

２．いろいろ考えたあげく、彼と別れることにした。

３．彼はサラ金からさんざん借金をしたあげく、ついに首が回らなくなって夜逃げをした。

４．父は長い間、病に苦しみ抜いた果てに、亡くなった。

５．彼は会社のために身を粉にして働いて、あげくの果てにリストラされてしまった。



★　例題　★

1）　苦労した（あげくに／末に）、（ついに／結局）念願のマイホームを手に（入れる／入れた）。

2）　返答（　）（窮する→　　　　　　）あげく、つい嘘をつい（てしまう→　　　　）。



(^^)前課の解答(^^)

1)　効いている（継続状態）／は／と（と＆時→文型203）

2)　に／している／に



## 003 ～上げる／～上がる



　　 他動詞：［ます］形　＋　上げる

　　 自動詞：［ます］形　＋　上がる



♪　会話　♪

佐藤：課長、遅くなりましたが、上海に出張の報告書ができ上がりました。御覧いただけますか。

課長：おう、書き上がったか。しかし、長いなあ。要約を一ページつけてから部長へ上げよう。

李　：君も今度のことでは大いに株を上げたな。こんなに難しい交渉をまとめたとは、ほんと、たいしたものだよ。



♯　解説　♭

　付属動詞「～上げる」は、「～を＜他動詞＞＋上げる」「～が＜自動詞＞＋上がる」という形になります。意味上は上方への移動、程度の強調、完了・完成の三つに分かれます。これは上への移動から上の極へ到達するにつれて、「完全に～」の意味の程度強調へ、更に完成・完了へと意味が拡大したものです。

　　＜上方へ移動＞

　～が飛び上がる・～が立ち上がる・～を見上げる・～を持ち上げる…

　　＜程度の強調＞

　～が晴れ上がる・～が震え上がる・～を鍛え上げる・～を磨き上げる…

　　＜完了・完成＞　　

　～ができあがる・～～が刷り上がる・～を書き上げる・～を育て上げる…



§　例文　§

１．合格の知らせを聞いた娘は、飛び上がって喜んだ。

２．見上げると、晴れ上がった青空を鳥たちが飛び交っていた。

３．武道で鍛え上げた男の体は、まるで鋼のようだった。

４．何カ月もかかって作り上げた作品を前にして、わたしは喜びがこみ上げてきた。

５．「おい、例のもの、でき上がったかい？」「細工は流々、仕上げをごろうじろ」



★　例題　★

1)　変わり果てた友の姿を見て、（思わず／ふと）涙（が／を）こみ上げ（てきた／ていった）。

2)　ご飯が（炊く→　　　　）上がったよ。みんな、仕事を（切る→　　　　）上げて食事（　）しないか。



(^^)前課の解答(^^)

1)　末に（→文型116）／ついに（期待したことの実現）／入れた

2)　に／窮した／てしまった（不本意の「～てしまった」）



## 004 ～あっての



名詞：　×　　＋　(が)あっての　＋　名詞



♪　会話　♪

部長：ありがとう。今回の受注は君たちのおかげだ。なんと言っても、仕事あっての会社だからな。

山田：いいえ、部長の御指導のたまものです。

部長：いやいや、そんなことはない。みんなの協力あっての成功だ。「チームワークこそ成功の鍵だ」と改めて教えられたよ。ありがとう、みんな。



♯　解説　♭

　「～あってのＮ」は「～があって、はじめて可能な Ｎ」という意味を表します。前の条件がなければ、後ろの結果も成立しないという前提条件を表す点で、「～て、はじめて／～て、こそ」（→文型192）、「～ば、こそ」（→文型050）と基本的には同じ意味になります。

　　みんなの協力　あっての　　　　成功だ。

　　　　　　　　　があってこその

　　　　　　　　　があればこその



§　例文　§

１．この度の優勝は、みんなの団結あってのものだ。

２．私が仕事に専念できるのも、全て妻の内助があってのことです。

３．彼女が会社を辞めたのは、きっと何かわけがあってのことだろう。

４．そりゃあ、お金も欲しいけど、「命あっての物種」って言うじゃないか。

５．お客あっての商いだということを忘れてはいけない。



★　例題　★

1)　○○先生（あるからの／あっての）私です。（お／ご）恩は（いつも／いつまでも）忘れません。

2)　専務があなたをこのパーティ（　）招待した（　）は、きっと何か考えがあって（　）ことですよ。



(^^)前課の解答(^^)

1)　思わず（自然な感情）／が（自Ｖ）／てきた（→文型181）

2)　炊き／切り／に（Ｎ＋にする：「何にする？」「僕はこれにする」）



## 005 ＊～あまり（に）



名詞　　　　：　　　の 　 　　＋　　あまり(に)

動詞・形容詞：普通形＜ナ形ーな＞



♪　会話　♪

百恵：最近、山田君、ちょっと変よ。何を聞いても上の空だし、仕事にも手がつかない感じだ。

李　：僕も心配のあまり尋ねてみたら、彼女に振られたらしいんだ。毎晩どこかで酔いつぶれているらしいよ。

百恵：寂しさのあまり、お酒で気を紛らわしてるのね。あまり飲みすぎると、体を壊しちゃうわよねえ。



♯　解説　♭

　この文型は「とても（程度が限度を越えている）～ので」を意味します。「ので」系の原因・理由の表現（→資料､）で、後件では発生した既定事実を表すので、「～つもりだ・～たい・～だろう」などの意志・希望・推量表現は使えません。なお「あまりのＮに」も「あまりに～ので」も同義表現です。 寂しさのあまり、 あまりに寂しいので、

　　　　あまりの寂しさに、

　　お酒で気を紛らわしているのね。



§　例文　§

１．うれしさのあまり、涙がでた。

２．急ぐあまり、家の鍵をかけるのを忘れてきてしまった。

３．彼は人がいいあまり、嫌な仕事を押しつけられても断りきれない。

４．慎重になり過ぎるあまり、チャンスを逃すこともある。

５．「可愛さ余って（＝可愛さのあまりに）憎さ百倍」という俗語がある。



★　例題　★

1)　一人の子供がいじめを告発する遺書を（残して／残って）自殺したという（ので／のに）、開き直る学校側の答弁に、私は怒り（あまりに／のあまり）体が震えた。

2)　彼はまじめ（　）あまり、（考える過ぎる→　　　　）り、（思い詰める→　　　　　）りするんだろう。



(^^)前課の解答(^^)

1)　あっての／ご／いつまでも（「いつも（×いつまでも）遅刻する」）

2)　に（～を～に招待する）／の（「～のは～ことだ」文型）／の



## 006 ～あろうことか（あるまいことか）



名詞　＋　は、あろうことか（あるまいことか）

あろうことか（あるまいことか） 、　　～



♪　会話　♪

李　：もしもし、良子？あろうことか、出発間際になって、急にフライトがキャンセルになっちゃってね。

良子：だから言ったでしょ。少しぐらい高くても、いつもの航空会社の方が安全だって。

李　：これから家に帰るよ。食事は済ませてあるから、夕食の支度はしなくてもいいよ。



♯　解説　♭

　この文型は「そんなことがあっていいだろうか（いや、あってはいけない）」という意味の反語表現です。事実は眼前に存在していますが、それを信じられないし、信じたくない気持ちがあり、非難・残念の感情を強く含んでいます。



§　例文　§

１．あの学生は、あろうことか、教師に暴力を振るった。

２．一部の報道記事には、あろうことか、あるまいことか、事実を捏造したものもある。

３．あろうことか、よりにもよってこの俺に、よくもそんな見え透いた嘘が言えたものだな。

４．日本の政治家の中には、あろうことか、先の戦争をアジア解放戦争だったと言う者がいる。

５．あろうことか、教師がテレクラ通いをしていたとは。



★　例題　★

1)　（ある／あろう／あるまい）ことか（ある／あろう／あるまい）ことか、不正入試事件（が／を）発覚した。

2)　（ある→　　　）ことか、遊ぶ金（ほしい→　　　）に売春をして、「どこが悪いの？」（　）うそぶく少女がいる。　　　　　　　（注：これを「援助交際」と現代語で言う）



(^^)前課の解答(^^)

1)　残して（～を＋他Ｖ）／のに（逆説）／のあまり（「怒り」はＮ）

2)　な（ナ形）／考え過ぎた（「～たり～たりする」文型／思い詰めた



## 007 いかに～ても／いかなる～ても



いかに　　　　　～ 動詞・形容詞：て形 ＜ナ形ーで＞　＋　も

いかなる＋名詞 　 名詞　 　 ：　　　　で

（注：「～ても」の他に「～ても」系の逆説は使える。 → 解説）



♪　会話　♪

良子：明日は模擬試験だったわね。焦ってるみたいだけど、まさか、今夜、徹夜するつもりじゃないでしょうね。

小孫：「いかに困難でも、またいかなる状況下にあっても、全力を尽くせ」って言うじゃないか。

良子：それは普段から勉強してない人が使う言葉じゃないわ。日本ではそんなのを「付け焼き刃」って言うのよ。



♯　解説　♭

　「いかに」「いかなるＮ」は「（前件の）事情・状況・程度がどうであっても関係なく、いつも・必ず（後件が）成立する」という条件表現で、書き言葉で多く使われます。「どんなに／いくら（＝いかに）～ても」「どんな（＝いかなる Ｎ）～ても」（→文型143）はその口語表現で、話し言葉ではこちら方が多く使われるでしょう。

　また、「ても」のほかに「～と言えども」（→文型216）、「～であろうと／～であれ」（→文型176）、「～（よ）うが／～（よ）うと」（→文型437）などの「ても」系逆説が使われます。



§　例文　§

１．いかに難しい問題でも、解けない問題はない。

２．いかなる時でも笑顔を忘れないでいれば、道は開けるよ。

３．いかなる人と言えども、欠点はあるものだ。

４．いかに人からあざ笑われようが、今はただ、信じた道を進むだけだ。

５．彼は勇敢な男だ。いかなる危険が待ちかまえていようとも、たじろいだりはしない。



★　例題　★

1)　（いかに／いかなる）障害にぶつかっ（たら／ても）、試練と（思えば／思って）、乗り越えていけるものだ。

2)　一人一人の力がいかに（小さい→　　　　）ても、力を（合わせる→　）ば、いかなる強敵でも（倒す→　　　）はずだ。



(^^)前課の解答(^^)

1)　あろう／あるまい／が（自Ｖ）

2)　あろう／ほしさ（イ形のＮの形：美しい→美しさ）／と（引用）



## 008 ～如何だ／～如何で／～如何によらず



名詞：　×　＋　　(の)如何だ　　　　　　　①

　　　　　　　　　(の)如何で

　　　　　　　　　(の)如何によって

名詞：　×　＋　　(の)如何にかかわらず　　②

　　　　　　　　　(の)如何によらず



♪　会話　♪

小孫：模擬試験の結果の如何によらず、志望校を受験したいんですが、間に合うでしょうか。

先生：君のこれからの努力如何で決まる思うよ。まだ、２ヵ月以上もあるからね。

小孫：ということは、可能性があるということですね。最善を尽くしてみます。



♯　解説　♭

　「如何」は「どうであるか」を意味する漢語で、根拠を示す助詞の「～で／～によって」と結びつくと「～ かどうかによって決まる」という意味を表し、「～に関係なく」を意味する「～にかかわらず」（→文型293）、「～によらず（→文型349）」や「～を問わず」（→文型472）」と結びつくと「 ～がどうかに関係なく～」という意味を表すようになります。

　この「如何」は例文中のもののほかにも慣用句がいくつかありますから、一緒に覚えた方がいいでしょう。

　　如何せん：如何せん、もはや救う手段がない。

　　如何ともしがたい：こうなっては如何ともしがたい。

　　如何にかかっている：成功するかどうかは、努力如何にかっている。



§　例文　§

１．その会社に就職するかどうかは、給料如何ですねえ。

２．酒というのは飲み方如何で、毒にもなり薬にもなる。

３．今後の君の態度如何では、懲戒解雇もあり得ることを忘れるな。

４．理由の如何を問わず（⇔如何によらず／如何にかかわらず）、暴力はよくない

５．今更そんなことを言われても、もう、手遅れだ。如何ともしがたいよ。



★　例題　★

1)　勝敗（が／の）如何（によって／にかかわらず）、両チームの健闘は讃えられる（はず／べき）だろう。

2)　業績如何（　）降職も（ある→　　　）得る人事制度が企業に（導入される→　　　　　）始めた。



(^^)前課の解答(^^)

1)　いかなる／ても（逆説・仮定）／思えば

2)　小さく／合わせれ／倒せる（可能形）



## 009 ＊～以上（は）



名詞　　　　：である　 　　　　 ＋ 　　以上(は)

動詞・形容詞：普通形＜ナ形ーな＞



♪　会話　♪

李　：日本人は「イエス」と「ノー」がはっきりしなくて困るよ。来る前に想像していた以上だ。

良子：以心伝心、察しの文化と言われる由縁ね。でも、「郷に入れば郷に従え」よ。

李　：なるほど、日本語を勉強する以上は、日本の文化も学ばなくちゃね。



♯　解説　♭

　「～以上（は）」は「～だから、当然・必ず ～」という意味を表す原因・理由表現で、文末には「～なければならない／～べきだ」（→文型382）や「～つもりだ」、「～たい」などの義務や意志・希望、「～はずだ」（→文型367）、「～にちがいない」（→文型305）などの断定判断が多く使われます。この場合は「～からには（→文型056」や）「～上は（→文型015）」と同義表現となります。

　しかし、「～以上」は因果関係がなくても、既定条件の場合に広く使えます。例えば、下の例文は条件（仮定）を表していますが、この場合、「～からには／～上は」は使えません。

　＊あなたの同意がない以上（＝なければ）、無断で掲載することはない。



§　例文　§

１．お話はわかりました。この件については、私どもが引き受けた以上、大船に乗ったつもりでいてください。

２．こうなった以上は、もう他に方法はない。

３．一旦契約書にサインをした以上、君の責任は避けられない。

４．彼がやらせてほしいと言う以上、見込みがあってのことだろう。やらせてみたらどうか。責任は私が負う。

５．私に刃向かう以上、それなりの覚悟はあるんだろうね。



★　例題　★

1)　父親（の／である）以上、娘がつきあっている相手（を／に）無関心では（いられる／いられない）よ。

2)　闘う以上、（負ける→　　　　　）たくないと思う（　）は人情だ。負ける（　）わかっているなら、最初（　）（　）闘わないことだ。これを「逃げるが勝ち」という。



(^^)前課の解答(^^)

1)　の／にかかわらず／べき（→文型382）

2)　で／あり（～得る：→文型017）／導入され（Ｖ〔ます〕形＋始める）



## 010 ＊～一方だ／＊～ばかりだ



名詞　　：　　の　　　＋　 一方だ

動詞　　：　原形　　　 　 　ばかりだ （＊名詞接続不可）

ナ形容詞：～になる

イ形容詞：～くなる

（注：「まじめ一方」 のような慣用的言い方もある）



♪　会話　♪

李　：産業活動の発展は目覚ましいけど、その反面で、公害は年々ひどくなるばかりだね。

良子：ほんとうね。海も川も汚れていく一方だし、森林破壊、酸性雨、砂漠化、地球温暖化と問題は山積みだわ。

李　：早く手を打たないと地球に生き物が住めなくなってしまうね。でも環境か開発か、難しい問題だなあ。



♯　解説　♭

　「～一方だ／～ばかりだ」は変化を表す語につき、変化が一つの方向に進行していること表します。

　ただし、「～一方だ」はいいことにも、良くないことにも広範に使えますが、「～ばかりだ」は「程度が～過ぎる」という語感をもっていて、例文３のようにいい傾向に使うと不自然になります。また、「～ばかりだ」は例文１のように名詞に接続する形がありません。



§　例文　§

１．今年に入り、株価は下落の一方（×ばかり）だ。

２．給料は下がる一方（⇔ばかり）、物価は上がる一方（⇔ばかり）、これじゃやっていけないよ。

３．彼はまじめ一方（×ばかり）の人で、よく言えば仕事一筋の人ですが、融通の利かないところが難点ですね。

４．老後のことを考えると、不安は募るばかり（⇔一方）だ。

５．ストレスが原因とみられる心の病気は、ますます深刻化するばかり（⇔一方）だ。



★　例題　★

1)　景気は落ち込む（だけ／ばかり）、雇用不安は増す（だけ／ばかり）で、明るい材料が（見あたる→　　　　　）。

2)　地球人口は年々増える一方（　）、21世紀の前半には百億を（越す→　）そう（　）勢いだ。



(^^)前課の解答(^^)

1)　である／に／いられない（→文型191）

2)　負け／の（→文型354）／と（内容を引用：～とわかる」／から



## 011 ＊～一方（で）



名詞　　　　：　　　　の 　　　 　　 ＋ 　　一方(で)

動詞・形容詞：普通形＜ナ形ーな＞



♪　会話　♪

課長：李君は仕事に熱心な一方で、仲間とのつき合いも大切にしているようだな。それに大変な恐妻家だとか。

山田：そうなんですよ。でも、奥さんに財布の紐を握られ、頭が上がらないというもっぱらの噂です。

課長：はっは、それが夫婦円満の秘訣さ。夫婦で力を合わせて、将来に備えているわけだ。



♯　解説　♭

　「～一方（で）」は「Ａは～、他の一面では～」同一主語の異なる面を表す場合にも、「Ａは～だが、反対にBは～」と主語が異なるものを対比させる場合にも使えます。

　類義語に「～かたわら」（→文型036）があり、例文１～３は置き換えることができます。また、例文４のように同一主語の対立する面を表す場合には「～反面」（→文型375）に置き換えることができます。ただし、この二つの文型は例文５のような異主語文では使えません。

　　姉は家庭的だが、一方（×反面）妹は活動的だ。　＜異主語文＞

　　父はいつも静かだが、一方（・反面）怒ると恐い。＜同一主語文＞



§　例文　§

１．彼は病院に勤める一方で、地域ではボランティア活動に参加している。

２．兄は勉強ができる一方、遊ぶことも忘れない。

３．表では争っているように見せる一方で、裏では手を結んでいるのが政治の世界だ。

４．日本経済については楽観的な見方がある一方で、今後は高成長は望めないという見方もある。

５．あの家庭は夫が遊び好きな一方で、妻はしっかり者だ。



★　例題　★

1)　アジア地域の経済発展は目覚ましい（が／のに）、（一方／反面）、所得格差が拡大（する／し）つつある。

2)　豊かな国々（　）益々（豊かだ→　　　　）なる一方で、貧しい国々が益々（貧しい→　　　　）なっている。



(^^)前課の解答(^^)

1)　ばかり／ばかり／見あたらない

2)　で／越し（Ｖ〔ます〕形＋そうだ＜様態＞／そうな



## 012 いわんや～においてをや／～まして～にはなおさらだ



いわんや ～ 名詞 ：　×　　＋　　においてをや

まして　　　　　　 　 　　　　　に(おいて)はなおさらだ



♪　会話　♪

李　：このパソコンの使い方がどうしてもよくわからないなあ。え～っと、マニュアル、どこにあったっけ？

良子：説明書を読むのもいいけど、山田さんに聞いてみたら？その方が手っ取り早いわよ。

李　：彼がひどい機械音痴だってこと知らないの？僕でさえ四苦八苦なのに、いわんや山田においてをやだよ。



♯　解説　♭

　「況（いわん）や」「況（まし）て」と助詞「～において」（→文型291）が結合した文型で、「Ａは～ 、だからＢは言うまでもなく、（もっと・更に）～」を意味する文語です。話し言葉としては「まして ～ には、なおさらだ」が多く使われるでしょう。

　専門家にさえ直せない。

　　→いわんや素人においてをや。

　　→まして素人にはなおさらだ。



§　例文　§

１．この高校入試問題は大学生の僕にさえ難しいのに、まして中学生にはなおさらです。

２．僕が子供の頃、日本の家庭にはテレビもなかった。ましてパソコンにおいてはなおさらだ。

３．彼は英語すら読めない。況やフランス語においてをや。

４．源氏物語を原書で読める日本人はそう多くない。いわんや外国人においてをやだよ。

５．約束は守るもの。いわんや首相の公約においてをやだ。



★　例題　★

1)　（これ／この）ほどの山と（する／なる）と、登るのは若者でも容易ではない。（だから／まして）老人においてをや。

2)　当時の私は食べ物に（　）（　）事欠く始末（だ→　　　）。（　）（　）（　）本を買う金などあろうはずがなかった。



(^^)前課の解答(^^)

1)　が（「～のに」は因果の逆説）／一方（反面も可）／続けて（他Ｖ）

2)　が／豊かに（ナ形＋なる）／貧しく（イ形＋なる）



## 013 ＊～上で／＊＊～後で



名詞：　の 　　＋　　上で

動詞：原形 　

名詞：　の 　　＋　　後(で)

動詞：た形　　　　　 上(で)



♪　会話　♪

銀行：御融資の件ですが、私の一存では決め兼ねます。本店の審査を仰いだ上で、お返事を差し上げます。

社長：そこをなんとか・・・。私も今回ばかりは無理を承知の上で、お願いに伺っています。

銀行：本店とも相談はしてみますが、御期待にそえるかどうかは、ここでは何とも申し上げようがございません。



♯　解説　♭

　「～上で」は二つの使い方があって、前が動詞で「原形」の時は「～する場合～」（方面・分野）を意味し、「た形」の時は「～た‐あとで」と同じ意味になります。ただし、前が名詞のときは文脈から理解するしかありません。

　なお、「～た‐上で」は人の意志動作を強調するので、自然現象や状態発生には使えませんし、「～た‐上で／～た‐後で」は継続事態を表すときには使えません。例えば「～てから」「～た‐後で」「～た‐上で」を比較すると、以下のような違いがあります。

　　風呂に入ってから（・た後で／・た上で）、寝た。　　　 ＜動作発生＞

　　家に帰ってから（・た後で／×た上で）、雨が降り出した。＜状態発生＞

　　離婚してから（×た後で／×上で）、ずっと一人暮らしだ。＜継続事態＞



§　例文　§

１．辞書は言葉を学習する上で欠かせないものだ。

２．形の上では夫婦でも、実際は家庭内別居というケースが増えている。

３．先の事件は、法律の上では犯罪にならなくても、道義的責任は免れない。

４．この問題は拙速な結論は避け、慎重に検討した上で（⇔後で）ということでいかがでしょうか。

５．採用か否かは面接の上（⇔後で）、決めることにする。



★　例題　★

1)　買う（か否か／や否や）は、実物を（見る／見た）上で決める。先ず品物を見せて（くれ／あげ）たまえ。

2)　いかに酔っ（ている→　　　）とはいえ、あのような暴言は酒の上で（　）過ちで済むこと（だ→　　　　　）。



(^^)前課の解答(^^)

1)　これ（これほど≒ここまで）／なる（→文型253）／まして

2)　すら（「さえ」も可）／だった／まして



## 014 ～上（に）



名詞　　　　：である 　　 　 　　　 　＋　　上(に)

動詞・形容詞：普通形＜ナ形ーな＞



♪　会話　♪

李　：もう遅いので、そろそろ失礼いたします。

田中：今日はお休みのところを、わざわざ遠いところをおいでいただいた上に、遅くまでお引き留めいたして・・・、それに何のおもてなしもできなくて・・・。

李　：いえいえ、ごちそうになった上、お土産までいただきまして、本当にありがとうございます。



♯　解説　♭

　「～上（に）」は「～ し、（それに ／しかも／更に） ～」と同義で、添加・累加の表現です。類義語に「～し、～」（→文型107）、「～も～ば、～も～」（→文型199）、「～ばかりか～」（→文型363）などがあります。

　　彼女は優しい上に、美しい。

　→彼女は優しいし、美しい。

　→彼女は優しくもあれば、美しくもある。

　→彼女は優しいばかりか、美しい。

　この文型は良いことには良いことを、悪いことには悪いことを添加・累加しないと誤文になります。例えば、「彼女は優しい上に、背が低い」は誤文です。



§　例文　§

１．このカメラは小型である上に、性能もすばらしい。

２．彼は弁が立つ上に、知恵と勇気を兼ね備えている。

３．お世話になった上に、送別会まで開いていただき、誠にありがとうございます。

４．わが家は手狭な上、子供も多くて、日曜日もゆっくりくつろげません。

５．生活が苦しい上に、妻の入院も重なって、もうどうしていいのかわかりません。



★　例題　★

1)　彼は頭がいい（上で／上に）、ユーモアもある（ので／のに）、女性（だけか／ばかりか）男性にも人気がある。

2)　この店は安い上（　）うまいので忘年会の会場（　）は打ってつけだが、一応みんなと相談した上（　）決めないか。



(^^)前課の解答(^^)

1)　か否か（→文型040／→文型428）／見た／くれ（→文型182）

2)　ていた（あのような＝過去）／の（格助詞＋のＮ）／ではない



## 015 ～上は



名詞　　　　：である 　　　 　＋　　上は

動詞・形容詞：普通形＜ナ形ーな＞



♪　会話　♪

社長：君、今回の不祥事の責任をどうとるつもりだ。このままでは、社内のけじめがつかないぞ。

部長：ひとえに私の監督不行き届きです。かくなる上はいかような処分でも・・・。

社長：君の辞表１枚で済む問題じゃない。会社の信用がかかっているのが、まだわからないのか！



♯　解説　♭

　「～上は」は「～だから、当然・必ず ～」と言う意味を表す原因・理由表現で、「～以上」（→文型009）、「～からには」（→文型056）と同義表現です。「～ 上は」は文語で硬い印象を与えますから、日常会話では「～以上」「～からには」の方が適切です。



§　例文　§

１．軍人である上は、戦場での上官の命令は絶対である。

２．日本に留学した上は、一日も早く日本の生活に慣れることだね。

３．君の協力が得られない上は、この計画は諦めるしかない。

４．ここまで証拠が揃った上は、包み隠さず、素直に話した方が刑も軽くなるぞ。

５．選挙民に公約した上は、政治家たるものに二言があってはならない。



★　例題　★

1)　日本代表に（選んだ／選ばれた）（上は／上に）、皆様の御期待に添う（べく／べき）全力を尽くします。

2)　たとえ不満で（ある→　　　　　）と、多数決で（決まる→　　　）上（　）、それに従うのが民主主義だ。



(^^)前課の解答(^^)

・　上に／ので／ばかりか

・　に／に／で（「上に」と「上で」の違いに注意）


## 016 ＊～うちに／＊～ないうちに



名詞　：　　　　　の 　　　　　　　　　 ＋　 うちに

動詞　： 普通形 （一般動詞は「ている」）　　　 うち(が／は)

形容詞：＜イ形：ーい・ーくない＞

　　　　＜ナ形：ーな・ーでない＞



♪　会話　♪

真理：さあさあ遠慮しないで、冷めないうちに召し上がれ。でも、お口に合うかしら？

佐藤：真理さんの手料理なら、冷めてもおいしいですよ。

真理： まあ、佐藤さんったらお上手ね！どんどんお代わりしてね。

佐藤：うまい！お袋の味を思い出しましたよ。



♯　解説　♭

　「～うちに」は「～の状態の間に ～する」という意味を表す表現で、「～間（あいだ）に」（→文型002）とほぼ同義表現ですが、状態変化に関心をおいたのが「～うちに」で、時間を問題にしたのが「～間に」です。

　どちらも動作・状態が継続中に発生したことを表すので、状態動詞（ある・いる・できる・わかる・要る）を除いて、「～ている」形か「～ない」形に接続します。また、時間だけを問題にするのであれば、「～ないうちに」は「～する前に」に置き換えることができます。

　　あなたが寝ている（×寝る）うちに、地震があったんですよ。

　　子供が帰らないうちに（≒ 子供が帰る前に）、掃除する。

　なお、「～うちに」＜事態完了＞と「～うちは」＜事態継続＞の関係は「～間に」と「～間は」と同じです。→例題1)2)



§　例文　§

１．鉄は熱いうちに打て。

２．あの先生の授業は退屈で、聞いているうちに、いつも眠くなる。

３．生きてるうちが花なのさ。死んで花実が咲くものか。

４．あ、もう五時ですね。暗くならないうちに帰りましょう。

５．そうそう、忘れないうちに話しておこう。実は・・・



★　例題　★

1)　うとうと（する／している）うち（に／は）、（つい／うっかり）畳にタバコの火を落として焦がしてしまった。

2)　この件につきましては、この場での即答は（いたす→　　　　　）兼ねますので、一旦会社に持ち帰り、上司と相談の上、一両日（　）うち（　）御連絡申し上げたいと思います。



(^^)前課の解答(^^)

1)　選ばれた（受身形）／上は／べく（→文型382／→文型385）

2)　あろう（未然形＋と：→文型437）／決まった／は



## 017 ＊～得る／＊～得ない



動詞：［ます］形　　＋ 得る

　　　　　　　　　　　 得ない



♪　会話　♪

百恵：ねえねえ、山田さんが昨夜ＵＦＯを見たって言ってたわよ。

李　：あり得ないよ。でも、嘘を付く男じゃないから、あいつの目の錯覚だろう。

百恵：まるっきしロマンがないんだから。この広い宇宙のどこかに宇宙人がいることだってあり得るわよ。



♯　解説　♭

　「～得る／～得ない」は可能表現の一種で、一般動詞につくときは可能形「～られる／～ られない」と意味はあまり変わりません。しかし、「話し得る」は状況から判断して「～話せる可能性がある」が本来の意味なので、単に能力を言うだけの「彼は英語が話せる」を「彼は英語が話し得る」とは言えません。

　また、「～得る／～得ない」は可能形が作れない「ある・できる」などの状態動詞や無意志性の自動詞について、「あり得る／あり得ない」「起こり得る／起こり得ない」のように「～する可能性がある／ない」ことを表します。

　　あり得る（＝存在する可能性がある／×あれる）

　　できうる（＝できる可能性がある／×できれる）



§　例文　§

１．人類が火星に移住するってことは、近い将来、起こり得ることだ。

２．私ができ得る限りのことは、喜んでいたしましょう。

３．これが今選択し得る最良の方法ではないでしょうか。

４．申し訳ないが、まだ公表し得る段階ではないので、あしからず。

５．彼ほどの財力があれば、なし得ないものはないと言っていいだろう。



★　例題　★

1)　考え（得る／兼ねる）限りの手は尽くし（ておいた／てみた）が、もはや倒産を免れる道は（絶った／絶たれた）。

2)　あなたの主張は支離滅裂で、私（　）は到底（納得す　る→　　　）（得る→　　　）。



(^^)前課の解答(^^)

1)　している／に／うっかり（不注意は「うっかり」）

2)　いたし（→文型044）／の／に（「うちに」と「うちは」の違いに注意）



## 018 ＊～おかげで／＊～おかげか／＊～おかげだ



名詞　　　　：　　　　の　　　　　 ＋　　おかげで

動詞・形容詞：普通形＜ナ形ーな＞　　　　 おかげだ

　　　　　　　　　　　　　　　　　　　　 おかげか



♪　会話　♪

母親：おかげさまで、息子も志望校に無事合格できました。本当に夢のようです。

先生：本人の努力のたまものですよ。本当によくがんばったと思います。

母親：いえいえ、先生のお力添えがなければ、とても・・・。全て先生のおかげです。



♯　解説　♭

　「～おかげで」は「～（の）援助・恩恵があって～」という意味を表す原因・理由の表現で、いい結果が生じたときに使われます。悪い結果が生じたとき使うのが「～せいで」（→文型122）、どちらの場合にも使えるのが「～ために」です。ただし、「～おかげで」は、例４のように皮肉・非難の気持ちを込めて使うことも希にあります。どれも「ので」系（→ 資料編､）なので、後件では発生した事実や確定事実を表し、「～つもりだ／～たい／～だろう」などの意志・希望・推量表現は使えません。

　理由が不確かなとき、断定を避けて「～おかげか」の形が使われます。なお、「おかげさまで」という語は文頭でしか使えず、接続助詞の用法や文末で「～おかげさまです」とは使えません。

　　先生のおかげで（×おかげさまで）、無事合格できました。

　　合格できたのは、先生のおかげです（×おかげさまです）。



§　例文　§

１．君が手伝ってくれたおかげで、仕事が早く片づいた。

２．私が今日あるのは、田中さんがあのとき助けてくださったおかげです。御恩は一生忘れません。

３．お前が一人前になれたのは、一体、誰のおかげだと思っているんだ。

４．あなたのおかげで、平気で嘘がつける女になれたわ。

５．先生の丁寧な教え方のおかげか、このクラスには落ちこぼれの学生は一人もいません。



★　例題　★

1)　一人っ子の（おかげか／せいか）、わがまま（が／に）育っ（てしまいました／ていました）。

2)　おかげさま（　）主人は軽い骨折で済んだのですが、あの事故（　）亡くなられた皆様のことを思う（　）・・・。



(^^)前課の解答(^^)

1)　得る／てみた（→文型197）／絶たれた（基運「受身」：→　Ｐ）

2)　に／納得し／得ない



## 019 ＊御～する／＊御～になる



御（お／ご）＋ 　動詞：［ます］形 　＋ 　する／いたす

　　　　　　　　　　　　　　　　 　　　になる／なさる

御（お／ご）＋ 　動詞：［ます］形 　＋　 ください

　　　　　　　　　　　　　　　　 　　　願えませんか

　　　　　　　　　　　　　　　　 　　　なさい



♪　会話　♪

李　：部長、田中様がお見えになりました。こちらにお通しいたしましょうか。

部長：うん、そうしてくれたまえ。

田中：突然お伺いいたしまして、御迷惑ではなかったでしょうか？

部長：いえいえ、そんなことはございません。さあ、どうぞ。



♯　解説　♭

　「（お／ご）～する／いたす」を謙譲形、「御（お／ご）～になる／なさる」を尊敬形とも呼びます。敬語は場面や相手によって複雑に変化しますので、一言で説明することは困難ですが、私は下げる（＝謙譲語）、相手は上げる（＝尊敬語）と覚えておくといいでしょう。

　「御」は「お」とも「ご」とも読みなす。　「お約束する・お料理する」や「ご案じになる・ご案じいたす」などの例外がありますが、一般に和語動詞には「お」、漢語動詞（「～する」動詞）には「ご」がつくと考えればいいでしょう。



§　例文　§

１．あのう、ちょっとお尋ねしますが、この近くに郵便局はないでしょうか。

２．申し訳ございませんが、もう少々、お待ち願えませんか。

３．私がご案内いたします。さあ、こちらへどうぞ。

４．では、ご主人がお帰りになられましたら、私の方にお電話くださるようお伝えいただけませんか。

５．当ホテルをご利用のお客様には、特別ディナー招待券を差し上げております。どうぞご利用ください。



★　例題　★

1)　お買い上げ（する／になる）かどうかはともかく、一度お（召し／召し上がり）（して／になって）みてください。

2)　どうぞ、お（入る→　　　　）ください。（　）（待つ　→　　　　　）しておりました。



(^^)前課の解答(^^)

1)　せいか（悪い結果）／に（変化の結果）／てしまいました（不本意）

2)　で／で（理由）／と（「お気の毒です」が省略・感情発生→文型203）



## 020 ＊～恐れがある



名詞　　　　：　　　　の 　 ＋ 　恐れがある

動詞・形容詞：普通形＜ナ形ーな＞



♪　会話　♪

良子：ねえねえ、今夜あたり関東地方に台風が上陸する恐れがあるそうよ。

李　：道理で雲行きが怪しいと思ったよ。早く帰って来て正解だったようだ。

良子：でも、ここらで一雨あった方がいいかもしれないわね。そうでないと、水不足の恐れもあることだし。



♯　解説　♭

　「～恐れがある」は「～（の）心配・不安・危険など＜良くないこと＞が起こる可能性がある」という意味で、否定は「～恐れはない」となります。「～かもしれない」と同じ意味です。しかし、「～かもしれない」はどのような場合にも使えますが、「～恐れがある」は悪い事態の発生の時にしか使えないという特徴があります。なお、この文型は「～兼ねない」（→文型043）とほぼ同義表現です。

　　台風が上陸するかもしれない。

　→台風が上陸する恐れがある。

　→台風が上陸し兼ねない。

　間違えやすいのは悪い傾向を表す「～嫌いがある」（→文型063）との違いですが、「～嫌いがある」は既定事実で、未来の推測ではありません。→例題1)



§　例文　§

１．この病気は伝染する恐れもあるから、気をつけてほしい。

２．地震の影響で津波の恐れがありますから、緊急に避難してください。

３．バーゲン品は安いが、品質が悪い恐れがある。

４．彼は口が軽いから、彼に話すと秘密が漏れる恐れもある。

５．この金融不安がこのまま続くと、最悪の場合、世界恐慌に発展する恐れがある。



★　例題　★

1)　この船は（この／あの）程度の浸水で沈没する（恐れ／嫌い）は（ないから／なくて）、慌てなくてもよい。

2)　未成年者の犯罪を警察力だけで（押さえる→　　　　）（込む→　　　　）とすれば、かえって事態を（悪化する　→　　　　　　　）恐れがある。



(^^)前課の解答(^^)

1)　になる／召し（お召しになる＝着る）／になって

2)　入り／お／待ち



## 021 ～落とす／～漏らす



動詞：［ます］形　　＋　　 落とす

　　　　　　　　　　　　　漏らす



♪　会話　♪

李　：大きな魚をとり逃したんだって？

山田：詰めが甘かったと言おうか、何と言おうか、契約までもう一歩のところまで行っていたんだが。あ～あ、土壇場で敵の大将を討ち漏らした武将の心境だよ。

李　：くよくよしてても仕方がないだろ。元気を出せよ。

山田：ああ、でも、逃げた魚は大きく見えるなあ。



♯　解説　♭

　「落とす」は「撃ち落とす・切り落とす・突き落とす…」など、「上から下へ落とす」のように原義に近いものや、「攻め落とす・泣き落とす・口説き落とす・競り落とす…」のように攻略して目的を達する意味の複合動詞も作ります。文法上大切なのはここで取り上げた「～するのを忘れてしまう」という意味を表す用法でしょう。この場合「～もらす」も同じように使えますが、「うっかり（不注意で）～し落とす」「注意していたのに～しもらす」と語感の違いがあります。

　なお、「～損なう／～損ねる／～誤る」（→文型125）との意味の違いに注意しましょう。→例題1)



§　例文　§

１．報告書は読み落としがないように、細部まで注意せよ。

２．君の意見は、問題の本質を見落としているよ。

３．入学願書に、大事な記載事項を書き漏らしてしまった。

４．そのことについては記憶がないんですが、聞き漏らしていたのかもしれません。

５．押して駄目なら引いてみな。それでも駄目なら、もう彼を口説き落とす手は、泣き落とし作戦しかないね。



★　例題　★

1)　四者択一の問題は、答えを（書く／書き）さえすれば、四分の一の可能性があるのだから、書き（損なわない／漏らさない）（ように／ことに）しなさい。

2)　試験場では受験番号の（書く→　　　）落としが（ある→　　　）よう、（注意する→　　　　　　）なさい。



(^^)前課の解答(^^)

1)　この／恐れ／ないから（文末が意志表現の時、「ので・て」は不可）

2)　押さえ（→文型094）／込もう（→文型441）／悪化させる（使役）



## 022 ～思いをする／～思いがする／～覚えがある



動詞・形容詞：普通形＜ナ形ーな＞　 ＋　　思いをする

　　　　　　　　　　　　　　　　　　　　 思いがする

　　　　　　　　　　　　　　　　　　　　 覚えがある



♪　会話　♪

李　：部長の仕事に賭ける情熱には、頭が下がる思いがするよ。正に仕事の鬼だね。

山田：でも頭ごなしに怒鳴られて、嫌な思いをした者も少なくないよ。僕もその一人だがね。

李　：僕は今までに、一度もそんな覚えはないなあ。

山田：たぶん、部長の覚えがめでたいんだろ。



♯　解説　♭

　「～思いをする」は話者の感情・感覚を表します。この表現は「悔しい思いをする→悔しく思う」のように言い換えることもできます。「～思いがする」は自然にわき上がる感情・感覚を表しますが、もともと「～がする」（→文型031）は人間の五感を表す文型です。

　なお、「～覚えがある」は 感情・感覚ではなく、「～記憶がある／～経験がある／～自信がある」などの意味を表します。→例題1)



§　例文　§

１．湯上がりに冷たいビールを飲むと、生き返る思いがする。

２．日本に来たばかりの頃は、何度となく不愉快な思いや、恥ずかしい思いをしたものだ。

３．車の運転にかけては、いささか腕に覚えがあります。

４．僕は君のやり方を批判したけれど、君自身の人格まで誹謗中傷した覚えはない。

５．あれほど触るなと言っておいたのに、このパソコンをいじったのは君だね。身に覚えがあるだろ？



★　例題　★

1)　私が歌手（にとって／として）一人立ちできる（までに／まで）は、ずいぶん辛い（思いもした／覚えもあった）。

2)　彼には確かどこ（　）で会った（ようだ→　　　　　）覚えがあるんだけど、どこで（だ→　　　　）っけ？



(^^)前課の解答(^^)

1)　書き（→文型100）／漏らす（～損なう：→125Ｐ）／ように

2)　書き／ない（～ように：→445Ｐ）／注意し（〔ます〕形＋なさい）



## 023 ～折り（に）



名詞　　　　：　　　　の 　 　＋ 　 折り(は)

動詞・形容詞：普通形＜ナ形ーな＞ 折りに(は)



♪　会話　♪

良子：先日、白石さんとお会いした折り、「また李君と一杯やりたいなあ」って言ってらしたわよ。

李　：そう言えば、卒業以来会ってないもんなあ。折りを見てこちらから連絡するよ。

良子：それがいいわ。学生時代はあんなに仲良しだったんだから。



♯　解説　♭

　「～折り（に）」は「～（の）とき」の意味で使われます。しかし、この「折り」は「機会」という語義も含んでいて、いくつかの慣用表現を持っています。

　　もし折りがあれば、またお会いしたいですね。→例題1)

　　私は折りにふれて詩を書きます。

　　折りも折り、うわさしていた彼が来た。

　類似表現に同じ時を表す「～（の）際」「～（の）節」（→文型098）がありますから、各項を参照してください。



§　例文　§

１．上京の折りには、御一報ください。

２．この件は今度会った折りにでも、また相談しましょう。

３．駅前で交通事故があった折り、たまたま僕はそこに居合わせた。

４．暑さも厳しい折から、くれぐれも御自愛ください。

５．折りもあろうに、こんな真夜中に電話をかけてくるなんて、なんと非常識な奴だ。



★　例題　★

1)　最近、忙しくて先生とお会い（する／になる）（折り／際）がない。君からよろしく伝え（ていて／ておいて）くれ。

2)　訪中（　）折りには色々お世話（になる→　　　　）まして、誠にありがとうございました。日本にお越し（　）節は、是非、御一報くださいませ。



(^^)前課の解答(^^)

1)　として（→文型237）／までに（→文型402）／思いもした

2)　か／ような／だった（副詞：「確か～だった／～した」の形）



## 024 ～かい（が）あって／～かいもなく／～がい



名詞：　の　　　　　　　＋　　かい(が)あって

動詞：た形・ている形　　　　　かいもなく

動詞：［ます］形　　　 　 ＋　　がい



♪　会話　♪

李　：今回のレコード即売会は出かけたかいがあったよ。念願のビートルズの古いアルバムが手に入ったからね。

良子：レコードだけが生きがいみたいねえ。

李　：会社で神経をすり減らしているんだ。寝ることと、レコード聴くことぐらいしか楽しみはないんだよ。

良子：何だか、寂しい人生ね。



♯　解説　♭

　「かい（甲斐）」は「効果・成果」や「意義・価値」という意味を表す名詞で、「～かい（が）あって」は例文1～3のように、動詞の「～した・～している」や名詞と結びつき、「～した効果・成果があって～した」という意味を表します。その否定表現は「～かいもなく」となります。どちらも文末が完了（「た」形）になることに注意しましょう。

　例文4、５のように動詞の「ます形」と結びつくのは接尾語で「がい」と読み、「～する十分な意義・価値がある」の意味を表します。例として「やりがい・鍛えがい・育てがい・生き甲斐・作りがい・読みがい…」などがあります。



§　例文　§

１．厳しい練習に耐えたかいがあって、ついに長年の念願であった優勝を勝ち取った。

２．合格おめでとう。がんばったかいがあったね。

３．彼は手術のかいもなく、亡くなった。

４．やるからには、やりがいのある仕事がしたい。

５．彼のような選手は鍛えがいもあり、育てがいもある。



★　例題　★

1)　（待つ／待ち）に待ったかいがあって、（ついに／結局）私にもチャンスが巡っ（てきた／ていった）（そうだ／ようだ）。

2)　もっと（教える→　　　）がいのある学生に（教える→　　　）たいものだ。これではやる気も湧い（てくる→　　　　　）。



(^^)前課の解答(^^)

1)　する（謙譲形）／折り／ておいて（基運「ておく」：→　Ｐ）

2)　の／になり／の



## 025 ～がいい／～がよい



動詞：原形／ない形　　＋　　がいい

　　　　　　　　　　　　　　がよい



♪　会話　♪

部長：今回の企画は一切を君に任せる。何かあっても責任は私がとるから、思う存分に腕を振るうがいい。

李　：任せていただき、ありがとうございます。部長の御期待にそえるよう、全力を尽くします。

部長：成功するかどうかは、君の肩にかかっている。では早速、取りかかりたまえ。



♯　解説　♭

　「～がいい／～がよい」は「～方がいい」と同じ提案・勧告の表現です。「～ばいい」や「～といい／～たらいい」（→文型154）も同じような意味を表しますし、「～するのが最善である／一番いい」と言う意味の文型「～に越したことはない」（→文型309）も類義表現です。

　その中で「～がいい」だけは少し特殊で、語調によっては例文５や「死にたければ、勝手に死ぬがいい」のように「勝手にしろ」という放任を表したり、話者自身のことには使えないなどの制約があります。



§　例文　§

１．言いたい奴には、好きなように言わせておくがいい。

２．身の程知らずの愚かな夢からは、早く覚めるがよい。

３．彼がそんなにほしがっているなら、やるがいい。

４．殺したければ殺すがよい。俺を殺しても歴史の歯車を止めることはできない。

５．そんな奥歯にものがはさまったような遠回しな言い方はやめろ。言いたいことがあれば、はっきり言うがいい。



★　例題　★

1)　もう僕には要らないもの（で／だから）、いくらでもほしい（だけ／ほど）持っ（てくる／ていく）がよい。

2)　僕の言葉がどうしても（信じられる→　　　　　　　）と言うなら、君自身の目（　）　確かめる（　）いい。



(^^)前課の解答(^^)

1)　待ち（→文型285）／ついに（期待した結果）／てきた／ようだ

2)　教え／教え／てこない（～てくる→文型181）



## 026 ＊～限り（は）／＊～ない限り（は）



名詞　　　　：である ／でない　 　＋　　限り(は)

動詞・形容詞：普通形＜ナ形ーな＞



♪　会話　♪

李　：部長からこの企画を任された限りは、なんとしても成功させたくてね。それで、君の力を借りたいんだけど。

真理：私にできることなら、何でもするわよ。

李　：今度の新商品は主婦層を対象にしたものなので、女性の視点から発想しない限り無理だと思ってね。

真理：一口に主婦層といっても、ニーズも多様化してるわ。



♯　解説　♭

　「～限り」は仮定と既定（理由）の接続助詞の働きをします。仮定の時は「～する間は絶対～」、既定の時は「～からには」（→文型056）や「～以上」（→文型009）と同様に「～だから、必ず～」を表す理由の表現になります。

　学生である　からには　勉強しろ。

　　　　　　　以上

　　　　　　　限り

　「～ない限り」は、例文４、５のように「（～する／～しない）間は、絶対～／～しなければ、絶対～」を意味するようになりますが、これは「～なければ」の強調表現と考えていいでしょう。



§　例文　§

１．生きている限り、先生から受けた御恩を忘れることはありません。

２．戦争が続く限り、人類の悲劇は終わらないだろう。

３．土下座でもして謝らない限り、決して彼を許さない。

４．相手方が非を認め賠償金を支払わない限り、我々は告訴することも辞さない。

５．彼は頑固だから、よほどのことがない限り、自分の説を変えることはないだろう。



★　例題　★

1)　使い捨ての消費文化（が／を）（変わる／変わらない）限り、ゴミ問題（を／が）根本的に解決されることはない。

2)　雨天（　）（ある→　　　　）限り、運動会は予定通り（行う→　　　　　）つもりです。



(^^)前課の解答(^^)

1)　だから／だけ （→文型131）／ていく（～ていく→文型177）

2)　信じられない／で（手段）／が（「と」も可→文型154）



## 027 ＊～限りだ



数詞・名詞：　　　　　× 　　　　　＋　　限りだ　　①

　　　　　　　　　　　　　　　　　　　　 限りで

感情形容詞：連体形＜ーい／ーな＞　 ＋　　限りだ　　②



♪　会話　♪

李　：田中教授の家は箱根に別荘があって、夏休みは家族そろって、そこで過ごすんだって。

良子：羨ましい限りだわ。お金って、ある所にはあるものね。「金は天下の回りもの」って言うけれど・・・。

李　：僕たちの所には回ってこないね。あ～あ、夏の休暇も今週限りだけど、どこにも行けそうにないなあ。



♯　解説　♭

　「～限りだ」は日時について「～までだ」＜期限＞、数量について「～だけだ」＜限定＞を表します。「限り」は名詞なので、「限りで～／限りの＜名詞＞」の形も使われます。

　また、「～限りだ」は感情形容詞につくと、「非常に～だ」という程度表現になります。多くの類義表現がありますが、代表的なものを挙げると、名詞に直接接続する「～極まる／～の極みだ／～極まりない」（→文型069）や、「～と言ったらない／（→文型219）」、「～のなんのって」（→文型358）や「～てたまらない／～てしかたがない」（→文型183）などです。

　　苦しい限りだ。

　　苦しいのなんのって。

　　苦しいと言ったらなかった。

　　苦しくてたまらない。



§　例文　§

１．この資料の貸し出しは、三日間限りです。

２．今日限りで、皆さんともお別れです。色々お世話になりました。

３．君と10年ぶりに再会できて、うれしい限りだ。

４．あんな奴に負けたなんて、くやしい限りだ。

５．根も葉もない噂をたてられ、腹立たしい限りだ。



★　例題　★

1)　一夜（限り／限って）の恋の（つもり／わけ）だったが、（いつしか／いつか）僕たちは深い仲へと発展し（ていった／てきた）。

2)　娘が（嫁ぐ→　　　　）からというもの、わが家はまるで火（　）消えた（ようだ→　　　　）静まり返り、寂　　しい限りです。



(^^)前課の解答(^^)

1)　が（自Ｖ）／変わらない／が（他Ｖの受身文）

2)　で／ない／行う（～つもりだ→文型175）



## 028 ＊～限りでは



動詞： 普通形　　＋　　限りでは



♪　会話　♪

李　：それって、今はやりのヨーヨーかい。面白そうだね、ちょっとやらせて。

小平：いいよ。でも、これってこつがあって、案外、難しいんだよ。

李　：やってるのを見た限りでは、それほど難しくなさそうだけれど・・・。あれっ？できないや！



♯　解説　♭

　「～限りでは」は「～範囲に限って言えば～」という意味で、後件で意見・判断や感想を表します。この文型が伝聞や判断の根拠の場合は、「～ところでは／～ところによると」（→文型233）を使って表すことができます。

　私が見た　限りでは　　それは本物のようです。

　　　　　　ところでは

　なお、「＜この／その＞限りではない」という否定の形は、「（前の文の内容の）範囲に限定されない」という意味を表します。



§　例文　§

１．私が診た限りでは、ただの風邪のようです。

２．私の知っている限りでは、彼女はまだ独身のはずです。

３．私が理解した限りでは、そもそもボタンの掛け違いから生じた問題ですね。

４．この度の殺人事件に関し、私の捜査した限りでは、Ａがきわめて黒に近いですね。

５．この病院の受け付けは午前中ですが、急患の場合はこの限りではありません。



★　例題　★

1)　私が聞いた（限っては／限りでは）、中国の都市部の変わり（方／よう）はすさまじい（こと／もの）がある。

2)　その記事（　）ざっと目を通した限り（　）（　）、これといって目新しい内容は（あった→　　　　　　）。



(^^)前課の解答(^^)

1)　限り／つもり（→文型175）／いつしか／ていった（→文型177）

2)　嫁いで（～てからというもの→文型180）／が（自Ｖ）／ように



## 029 ＊～かけだ／＊～かける／＊～かけの



動詞：［ます］形　　＋　　かける

　　　　　　　　　　　　 かけの　＋　名詞

　　　　　　　　　　　　 かけだ



♪　会話　♪

李　：おい、おい、言いかけた話を途中でやめるなよ。気になるじゃないか。

良子：きっとあなたは怒るから、やはりやめとくわ。

李　：よけい気になるよ。もったいぶらないで言いなよ。絶対怒らないからさ。

良子：実は、10万円のダイヤの指輪を買っちゃったの。



♯　解説　♭

　「～かけだ／～かけ」 は継続動詞＜多くは他動詞＞につくと「～している途中」や「～し始める」など開始や途中の状態を表し、瞬間動詞＜多くは自動詞＞につくと「～しそうになる」＜直前状態＞を表す表現になります。

　今、書きかけたところだ。　＜他動詞：開始＞

　書きかけの原稿があった。　＜他動詞：途中＞

　危うく死にかけた。　　　　＜自動詞：直前＞

　この他に、「～に話しかける・～に呼びかける・～に立てかける…」などのように「（対象）に～する」という意味もありますが、少数の動詞にしかつきませんから、語彙として覚えた方がいいでしょう。



§　例文　§

１．やりかけたことは、最後までやり通せ。

２．私が海で危うく溺れかけたところを、助けてくれたのが今の夫なんです。

３．もう日も沈みかけている。道を急ごう。

４．僕がうとうとしかけると、突然電話のベルが鳴った。

５．友達が遊びに来ると、息子は昼御飯も食べかけのまま飛び出していった。



★　例題　★

1)　臭いを嗅いで御覧よ。この肉はちょっと（腐る／腐り）（抜いて／かけて）いる（らしい／みたいだ）よ。

2)　せっかく（まとまる→　　　　　）かけた話が、君の不用意な一言（　）（壊れる→　　　）ようとしている。



(^^)前課の解答(^^)

1)　限りでは／よう（→文型435）／もの（→文型419）

2)　に（慣用：～に目を通す）／では／なかった（→文型095）



## 030 ～が最後／～たら最後



これ・それ・あれ：　　　×　　　　　＋　　が最後

動詞　　　　　　：た形（希に原形）

動詞　　　　　　：た形　　　　　　　＋　　ら最後



♪　会話　♪

佐藤：アメリカに２、３年行かないかって言われて、迷ってるんだ。行ったが最後、しばらく帰してもらえない気がしてね。

真理：出世コースじゃないの。このチャンスを逃したら最後、二度と回って来ないわよ。

佐藤：君も一緒に行ってくれないか？どう？



♯　解説　♭

　「～が最後／～たら最後」は「～が最後で、もう終わりだ」など、絶望的な結果になることを表します。文末で可能形の否定（「～できない／～（ら）れない」）が多く現れます。

　類義文型に後件で悪い結果が発生することを強調する仮定表現「～（よ）うものなら」（→文型448）がありますが、「～が最後／～たら最後」は確定事実であることが強調されていて、「もし／もしも／万一」といっしょに使えません。しかし、「もし～（よ）うものなら」は成立します。→例題1)

　そんなことを　　言ったが最後、　　この国では刑務所行きだ。

　　　　　　　　　言ったら最後、

　　　　　　　　　言おうものなら、



§　例文　§

１．あの男はこの業界の顔役で、彼ににらまれたら最後だ。

２．今度の仕事は少しでもミスをしたが最後、取り返しがつかないことになる。

３．彼は言い出したら最後、一歩も後へ引かない。

４．あいつはマイクを握ったが最後、離そうとしないカラオケ狂だ。

５．あんな女につかまったら最後、骨の髄までしゃぶられてしまうぞ。



★　例題　★

1)　万一大地震でも（起ころう／起こった）（が最後／ものなら）、この地域は地盤沈没の（嫌い／恐れ）がある。

2)　一旦（落後する→　　　　　）が最後、なかなか（はう→　　　　）上がれない（　）がこの競争社会だ。



(^^)前課の解答(^^)

1)　腐り／かけて／みたいだ（→文型408）

2)　まとまり／で（理由）／壊れ（→文型441）



## 031 ＊～がする



五感・感覚を表す名詞 ：　×　　＋　　がする

　　　　　　　　　　　　　　　　　　 がしない



♪　会話　♪

李　：あれっ、どうしたの？なんだか顔色が悪いような気がするなあ。

百恵：ええ、夕べから少し寒気がするの。

李　：どれどれ、あれっ、すごい熱だ。早退して医者に行った方がいいよ。仕事も大切だけど、体を壊しちゃ元も子もないよ。



♯　解説　♭

　「～がする」は「～を感じる」を意味しますが、前につく名詞は「味・臭い・声・音・～感じ・気・寒気・光…」など、五感で直接感じる対象です。

　「不安・怒り・喜び・危険」など抽象的・心理的対象は「不安を感じる」のように「～を感じる」を使います。この表現は「～を覚（おぼ）える」を使っても表せますが、少し古い言い方になります。→例題1)



§　例文　§

１．隣は今留守のはずなのに、人の声がしました。

２．誰でも褒められたら悪い気はしないものだ。

３．私の家は道路の側にあるので、真夜中まで車の音がして、慣れないうちは眠れなかった。

４．なんだか変な味がするよ。これ腐ってるんじゃないか。

５．第六感というか、嫌なことが起こりそうな感じがする。



★　例題　★

1)　あっ、稲光が（感じた／した）わ。夕立になるかもしれない（から／ので）、ねえ、あなた、早く帰り（ます／ましょう）よ。

2)　同じ過ち（　）何度も繰り返す（　）は、あきれ果てて、怒る気も（する→　　　　）。



(^^)前課の解答(^^)

1)　起ころう／ものなら（「万一～」は仮定文型）／恐れ（→文型020）

2)　落後した／はい（→文型003）／の（→文型354）



## 032 ～かそこら／～辺り／～足らず／～余り



数詞：　×　　＋　　かそこら　　①

名詞：　×　　＋　　辺り　　　　②

数詞：　×　　＋　　足らず　　　③

数詞：　×　　＋　　余り　　　　④



♪　会話　♪

良子：あ～あ、寒い。今朝なんか五度かそこらだったのじゃないかしら。マフラーを買わなきゃ。

李　：この辺りにはセンスのいい店がないね。アメ横辺りで買えば一万円でお釣りが来るだろう。行ってみる？

良子：買ってもらえるなら、どこでもいいわよ。いつものあそこで、５時半に待ち合わせましょうよ。



♯　解説　♭

　接尾語「～かそこら」は「～くらい」（→文型071）と同義ですが、その数量を軽視する話者の受け止め方があります。ですから、「この家は五千万円かそこらで買えるよ」と言えば、その人にとって五千万円は大金ではありません。

　ここで概数を表す表現＜数量詞＋くらい・かそこら・ほど・ばかり・足らず・余り＞を整理しておきましょう。

　　十日±α　　＝　十日かそこら

　　十日≧α　　＝　十日足らず

　　十日≦α　　＝　十日余り

　「～辺り」は名詞（時／ところ／人／こ・そ・あ）について大体の見当・推測を表すのですが、「付近・周囲」という意味の「辺り」から派生しています。



§　例文　§

１．東京から京都まで、あっという間だよ。新幹線で三時間かそこらで着くんだから。

２．あなたにとっては十万円かそこらは小遣い銭でも、私にとっては大金よ。

３．駅まではあっても二キロ足らずだよ。歩いて行こうよ。

４．この仕事には田中君辺りが、適任ではないでしょうか。

５．確か、ここら辺りに置いたはずなんだが、ないなあ。



★　例題　★

1)　来年（かそこら／辺り）、大阪支店に転勤という（ことになる／ことになり）そうだから、その（つもり／はず）でいてくれ。

2)　10分余り（　）仕事も片づくから、ちょっとここ（　）待っていて（いただく→　　　　）ないかしら？



(^^)前課の解答(^^)

1)　した／から（文末が意志表現）／ましょう（勧誘・提案）

2)　を（他Ｖ）／と（～とは②→文型242）／しない



## 033 ＊～か、それとも～か／＊～か、或いは～か／～か、または～か



名詞　　　　：　　　　×　　　　　＋　　か、それとも～か

動詞・形容詞：普通形＜ナ形ー×＞　　　　か、或いは

　　　　　　　　　　　　　　　　　　　　か、または



♪　会話　♪

良子：小平も一人部屋をほしがってるし、広い所に引っ越すか、それとも思い切ってマンションを買うか、決めなくてはいけないわね。

李　：今の給料じゃ、どちらも無理だよ。

良子：あ～あ、甲斐性のない夫を持つと、妻が苦労するわねえ。いっそ、夫を取り換えようかしら？



♯　解説　♭

　これらの文型は例文１～３のように疑問句ＡとＢを対比させ、どちらか一方の選択を求める場合に用います。この場合、「Ａか、それともＢ」「Ａか、或いはＢか」「Ａか、またはＢか」は同じように使えます。

　しかし、「それとも」は二者択一の時にしか使えません。なお、「或いは」「または」には例文４、５のようにそれ以外の用法があり、その場合には「それとも」が使えません。それ以外に次のような違いがあります。→例題1)

　＜AもＢも、どちらも＞

　　英語も、或いは（×それとも／×または）中国語も通じない。

　＜AでもBでも、どちらでもいい＞

　　円或いは（×それとも／○または）ドルで支払ってください。



§　例文　§

１．バスで帰ろうか、それとも歩いて帰ろうか？

２．中華料理にするの、それとも和食にするの。

３．突撃して活路を開くのか、或いは降伏して命ごいをするのか、もはや道は二つに一つだ。

４．泣いて詫びようが、或いは（×または／×それとも）いくら慰謝料を払おうが、君の犯した罪は消えない。

５．この署名欄には、日本語か、または（⇔或いは／×それとも）英語で御記入ください。



★　例題　★

1)　海外ビジネス（において／について）は、現地語（または／それとも）英語ができ（なくて／ないと）困る。

2)　参加するの（　）、それともしないの（　）、この場ではっきり返事をして（もらう→　　　　　）ませんか。



(^^)前課の解答(^^)

1)　辺り（「Ｎ＋」に注意）／ことになり（様態の「そうだ」）／つもり

2)　で／で／いただけ（可能形を使うと依頼）



## 034 ＊～難い



動詞：［ます］形　　＋　難い



♪　会話　♪

佐藤：初代の中国事務所の所長を、課長から打診されたんだけど、日本は住みやすいので離れたくないよ。

李　：離れ難いのは日本ではなくて、真理さんなのと違うかい？でも、どこでも「住めば都」だよ。

佐藤：所長だなんて急に言われても、にわかには受け難いよ。気持ちの準備もできていないしさ。



♯　解説　♭

　「～難い」は「～するのが困難だ」と意味ですが、人間の心理・思考面を表していて、実際は「しようとしても～できない」不可能な事態を表します。この点が類義表現「～にくい」（→文型306）との大きな違いで、「～にくい」は「難しいが、しようと思えば～できる」事態を表しています。→例題1)

　　その要求は受け入れ難い。　≒　受け入れられない

　　その要求は受け入れにくい。≒　受け入れられないことはない



§　例文　§

１．信じ難いことだが、彼は会社の金を使い込んでいたそうだ。

２．彼は得難い人材だ。会社の将来は彼のような若者の肩にかかっている。

３．耐え難きを耐えてこそ、忍耐と言える。

４．これはちょっと言葉では表し難い珍味ですなあ。

５．君の企画案は単なる思いつきに過ぎず、具体的なプランもない。これでは採用し難いね。



★　例題　★

1)　もしこの交渉（が／を）決裂（すれば／しても）、両国の全面的な軍事衝突は、もはや避け（難く／にくく）なる。

2)　香港の夜景の（美しい→　　　　）は、正に筆舌（　）（尽くす→　　　　）　難いものだった。



(^^)前課の解答(^^)

1)　において（→文型291）／または／ないと（理由か条件か）

2)　か／か／もらえ（可能形を使った依頼）



## 035 ～かたがた



名詞：　×　　＋　　かたがた



♪　会話　♪

山田：打ち合わせを早めに切り上げて、工場見学かたがたお花見に行かないか。夕日を浴びながらのお花見。たまにはのんびりしようじゃないか。

佐藤：おやおや、お花見かたがたの工場見学と言った方が正確じゃないの？困った方々だなあ。

山田：行きたいなら、がたがた言わないこと！



♯　解説　♭

　「～かたがた」は「ＡかたがたＢ」の形をとり、同一主語文で使われ、同一時間帯のなかで「Ａをする機会を使って、Ｂをする」並行動作を表します。丁寧な語感なので、手紙や公式の会話で多く使われます。同義表現に「～がてら」（→文型038）があり、こちらは日常会話で 多く使われます。どちらも動作Ａが主で動作Ｂが従の関係にあります。

　　　散歩かたがた（・がてら）、話しましょう。

　「ＡついでにＢ」（→文型163）も似た意味を表しますが、Ｂは付け足しの行為で異なる時間帯の動作です。→例題1)



§　例文　§

１．夕涼みかたがた、図書館に寄ってみた。

２．墓参りかたがた、幼友だちに会って来ようと思う。

３．お願いかたがた、近況御報告まで。　敬具

４．近くに来るついでがございましたので、先日のお礼かたがた、お伺いしました。

５．上海出張かたがた、足を伸ばして黄山に登ってきた。



★　例題　★

1)　近日中に（お／ご）挨拶（のついでに／かたがた）、（お　　／ご）伺い（になりたい／したい）と思っ（ております／ていらっしゃいます）。

2)　お寺参り（　）かたがた、浅草へ（遊ぶ→　　　　）に（行く→　　　　　）みませんか。



(^^)前課の解答(^^)

1)　が（自Ｖ）／すれば／難く（不可能の意味の方が自然）

2)　美しさ（Ｎの形）／に／尽くし（「筆舌に尽くしがたい」は慣用語）



## 036 ～かたわら



名詞：　の 　　＋　 　かたわら

動詞：原形



♪　会話　♪

課長：新聞でも紹介されていたけど、田中さんは仕事のかたわら、自治会の会長としても地域で大活躍だね。李　 ：奥さんも、中国帰国者に日本語を教えているボランティアグループのリーダーらしいです。

課長：有能な男のかたわらに良妻ありというところだな。君も地域活動で中国語を活かしてみたら？



♯　解説　♭

　「ＡかたわらＢ」は「Ａする一方でＢする」とほぼ同義表現ですが、動作Ａと動作Ｂは異なる時間帯で行われ、しかも習慣的な行為に用いることが多いでしょう。この点がＡとＢが同一時間帯で行われる並行動作を表す「～ながら」（→文型269）と異なっています。→例題1)

　　歩きながら（×かたわら）タバコを吸う。

　その他、「かたわら」には会話中の「男の傍（かたわ）ら」や「母が料理を作るかたわらで、子供たちが遊んでいる」のように「側」という場所も表します。



§　例文　§

１．彼は会社に勤めるかたわら、英語学校で勉強している。

２．Ａ社は不動産業のかたわら、飲食店も経営している。

３．あの人は農業のかたわら、農閑期は演奏活動もしているシンガー・ソング・ライターよ。

４．あいつは嫌な奴だ。本人の前では胡麻をするかたわら、裏で陰口をたたいている。

５．子育てのかたわら書きつづった随筆が、ベストセラーになった。



★　例題　★

1)　休日（ぐらい／ほど）は、音楽でも（聴きながら／聴くかたわら）、のんびり過ごしたい（こと／もの）だ。

2)　留学生の（多い→　　　）は大学（　）通うかたわら、学費を稼ぐ（　）（　）にアルバイトもしている。



(^^)前課の解答(^^)

1)　ご／かたがた（～ついでに→文型163）／お／したい／ております

2)　×／遊び（「ます形＋に行く」）／行って（→文型197）



## 037 ＊～がちだ



名詞：　×　　　　　＋　　 がちだ

動詞：［ます］形　　　　 　 がちなことだ

　　　　　　　　　　　　　 がちの　　＋　　名詞



♪　会話　♪

課長：君、この頃元気がないね。いつもの君らしくないので、部長と心配しているのだよ。

李　：子供がよく熱を出すので、どこか悪いのではないかと心配で。医者は何でもないと言っているのですが。

課長：子育てに慣れないうちは、親もあれこれ悩みがちだが、小さな子にはありがちなことだよ。



♯　解説　♭

　「～がちだ」は「～する傾向がある」「よく＜回数＞～する」という意味を表す表現で、述べられることは良くない傾向です。例えば、下の例のように良い傾向には「よく～する」を使ってください。○　あの人は、よく公園をジョギングしている。×　あの人は、公園をジョギングしがちだ。

　ほぼ同義語に性向を表す「～嫌いがある」（→文型063）がありますが、この表現は回数が多いことや一時的現象には使えません。



§　例文　§

１．この種の間違いは、初心者にありがちなことだ。

２．この子は小さい頃から病気がちで、しょっちゅう医者通いをしていました。

３．明日は午後から、曇りがちの天気になるでしょう。

４．疲れているときは、不注意による事故が起こりがちだ。

５．ふと浮かんだアイディアというのは忘れがちだから、必ずメモに残すことにしている。



★　例題　★

1)　若いうち（は／に）、正義心から、（とかく／とにかく）極端に（走る／走り）がちだが、理想論だけで世の中は変わる（こと／もの）じゃないんだよ。

2)　その人は遠慮（　）（　）に、　「あのう、ここ（　）タバコを吸ってもいいですか」（　）私に聞いた。



(^^)前課の解答(^^)

1)　ぐらい（最低限→文型072）／聞きながら／もの（→文型130）

2)　多く（「多く」はＮ）／に／ため（目的の「ため｝→文型152）



## 038 ～がてら



名詞：　×　　　　　＋　 　 がてら

動詞：［ます］形



♪　会話　♪

李　 ：夕涼みがてら、井の頭公園でも散歩しないか。

良子：男の人って優雅でいいわねえ。女の私はどこへ行くにも買い物がてらよ。

李　：わかった、わかった。ついでに吉祥寺の街に出て、夕食の材料も買って来よう。荷物は僕が持つからさ。

良子：ねえ、夏物の服も買っていいかしら？



♯　解説　♭

　「～がてら」は「Ａをしている時間を使って、Ｂをする」と言う意味を表す表現で、同一時間帯のなかで、主たる動作Ａに並行して、従たる動作Ｂをすることを表現します。

　また、同義表現の「～かたがた」（→文型035）、「～ついでに」（→文型163）も併せて参照してください。なお、このふたつの文型は同時並行動作は表せません。

　散歩がてら（・かたがた／・ のついでに）本屋に寄る。

　散歩がてら（・かたがた／×のついでに）話をしよう。



§　例文　§

１．神社のお祭りを見物がてら、夜店でものぞいてこようよ。

２．中国旅行がてら、教え子に会って来ようかと思う。

３．私は毎朝この道をジョギングがてら、思い浮かんだことを俳句にしている。

４．市場調査がてら都内の繁華街を冷やかして歩くのが、まあ、私の道楽のようなものです。

５．料理を作りがてら、聞くともなく聞いていたラジオから、　　懐かしい歌が流れてきた。



★　例題　★

1)　Ａ君は病気療養中との（こと／もの）だから、見舞い（ながら／がてら）、家に寄って（みる／みよう）よ。

2)　（散歩する→　　　　　　）がてら、古本屋に（寄る→　　　　　　　）、本を数冊（買う→　　　　）来た。



(^^)前課の解答(^^)

1)　は／とかく（傾向）／走り／もの（～ものではない→文型420）

2)　がち／で／と（内容・発言を取り上げる「と｝）



## 039 ～かと言うと／～かと言えば



なぜ　　～　名詞　　　　：　　　　×　　　　　＋　かと言うと

どう　　　　動詞・形容詞：普通形＜ナ形 ー×＞　　 かと言えば

どうして

どちら



♪　会話　♪

李　：ねえ、どちらの服が似合う？

良子：どちらかと言えば、右手に持っている明るい色の方がいいと思うわ。若々しくていいんじゃない？

李　：少し派手じゃないか？

良子：そんなことないわよ。日本のサラリーマンは黒っぽいのとか、灰色っぽいのとか、とにかく地味すぎるのよ。



♯　解説　♭

　「～かと言うと／～かと言えば」は疑問詞と呼応して、「～のことに関して語れば」という意味を表します。多くは「なぜ～かと言うと～からだ／どうして～かと言えば～からだ」のように理由を述べることが多いのですが、「どう／どちら／どんな…」などとも一緒に使うことができます。

　なお、「なぜかと言うと／どうしてかと言うと」などの接続詞もここから生まれています。例文５のように、希に疑問詞を含まない用例もありますが、相手方にとって意外なこと、想像もしなかったことを表すことが多いでしょう。



§　例文　§

１．どちらが好きかと言えば、やはり僕はこちらの方ですね。

２．誰が適任かと言えば、やはり山田君以外にいないだろう。

３．日本語の学習にはどんな方法が一番いいかと言うと、とにかく丸ごと暗記することでしょうね。

４．成功の秘訣ですか？どうすれば夢を実現できるかと言うと、そうですねえ、夢を持ち続けることでしょうね。

５．親が教師だから、その息子も勉強ができるかと言えば、　　そうとばかりは言えないようです。



★　例題　★

1)　なぜ僕（は／が）怒っているかと（言えば／言って）、君が自分の失敗を人のせいに（する／しよう）とするからだ。

2)　お金があるから幸せ（　）と言う（　）、一概にそうとは（言える→　）わけです。



(^^)前課の解答(^^)

1)　こと（～とのことだ→文型209）／がてら／みよう（勧誘・提案）

2)　散歩し／寄って（＝～て、それから）／買って（→文型181）



## 040 ＊～かどうか／～か否か



名詞　　　　：　　　　×　　　　 ＋ か否か

動詞・形容詞：普通形＜ナ形ー×＞　　 かどうか

　　　　　　　　　　　　　　　　　　 かどうかにかかっている

　　　　　　　　　　　　　　　　　　 か否かにかかっている



♪　会話　♪

良子：その人が成功するか否かは、何によって決まるのかしら。あなた、どう思う？

李　：才能があるかどうかじゃないのかなあ。いくら努力しても駄目な人もいるしね。それに運もあるなあ。

良子：でも、「玉磨かざれば光なし」って言うし、努力なくして成功はあり得ないと思うわ。



♯　解説　♭

　「～か否か」は文語表現で、口語の「～かどうか」と同義です。また例文５のように「（～かどうか／～か否か／～如何）にかかっている」の形もよく使われますが、この「～にかかっている」は「～によって決まる」を意味します。

　合格するかどうか（・か否か）は、努力するか（・か否か）にかかっている。



§　例文　§

１．それが事実かどうか、調査する必要がある。

２．賛成か否か、自分の意見をはっきり言いなさい。どっちつかずは卑怯です。

３．原発を存続させるか否かをめぐって、国論は真っ二つに割れている。

４．やるか否かは、状況如何にかかっている。

５．この製品が売れるかどうかは、宣伝が充分かどうかにかかっている。



★　例題　★

1)　勝てる（や否や／か否か）は天（のみ／しか）ぞ知るだよ。やってみなく（たって／ちゃ）わからないさ。

2)　おいしい（　）どう（　）は食べてみればわかる。実践　　こそ真理に近づく道では（ある→　　　）まいか。



(^^)前課の解答(^^)

1)　が／と言えば／しよう（→文型441）

2)　か／と／言えない（陳述副詞：一概に～とは言えない）



## 041 ＊～かと思うと／＊～かと思いきや／～かと見ると



名詞　　　　：　　　　×　　　　 ＋ かと思うと／かと思えば

動詞・形容詞：普通形＜ナ形 ー×＞　 かと思ったら

　　　　　　　　　　　　　　　　　　 かと思いきや

　　　　　　　　　　　　　　　　　　 かと見ると／かと見れば

（注：「～(の)かと思うと」のように「の」が入ることもある）



♪　会話　♪

真理：さっきのお客さん、入ってきたかと思ったら、いきなり大声で文句を言い始めたんだから。

李　：ゆゆしき一大事かと思いきや、結局はどういうこともなかったね。よかった、よかった。

百恵：そうかと思うと昨日みたいに、言葉少なでも迫力があって恐いお客さんもいるわね。



♯　解説　♭

　これらの文型は「～（だろう）かと思ったら、意外にも～した／だった」という予想外の事態の発生を表します。どれも既定事実の表現なので、文末は完了形（「た」形）になります。「～かと見ると・～かと見れば」は視覚判断が強調されていますが、「～かと思うと・～かと思えば」と基本的な意味は同じです。なお、「～かと思いきや」は「～かと思うと」の文語的表現です。

　「か」のない「～と思うと／と思ったら／と思いきや」の形も使われますが、そのときの接続は次の通りです。

　名詞　：　　　だ　　 　　 と思うと

　動詞　：　　普通形　　　　　＋　と思ったら

　形容詞：普通形＜ナ形ーだ＞　　　と思いきや



§　例文　§

１．静かなので勉強してるのかと思うと、ぐうぐう寝ていた。

２．右かと見れば左から、左かと見れば右から、そのボクサーは多彩なパンチを繰り出した。

３．怒るのかと思いきや、なんと笑い出したではないか。

４．もう出かけたかと思ったら、まだ家でぐずぐずしていたのか。急がないと遅れるぞ。

５．一つ解決したかと思うと、また一つと、次から次に問題が出てくる。



★　例題　★

1)　この子（って／ったら）、さっき（まで／までに）泣いてたかと思ったら、（もう／まだ）笑ってるわ。

2)　彼は（怒る→　　　　）出した（　）と思いきや、突然（立つ→　　　　）上がり、私に握手を求めてきた。



(^^)前課の解答(^^)

1)　か否か／のみ／みなくちゃ（口語：～ちゃ＝ては／～たって＝ても）

2)　か／か／ある（～まい→文型398）



## 042 ＊～か～ない（かの）うちに／～か～ないかに



動詞：原形　　＋　　か、動詞：ない形　　＋　　かのうちに

　　　　　　　　　　　　　　　　　　　　　　　 うちに

　　　　　　　　　　　　　　　　　　　　　　　 かに



♪　会話　♪

小平：あれ、まだ八時か。夕御飯から一時間たつかたたないかなのに、なんだかお腹が空いたなあ。

良子：今、食器を洗い終わったばかりなのに・・・。

小平：口に入る物なら何でもいいから、何かないの？

良子：あ～あ、片づくか片づかないうちに、またそんなことを言われてもねえ。これじゃ気が休まる暇もないわ。



♯　解説　♭

　これらの文型は「～すると、すぐ～した」（連続発生）という意味を表します。既定事実なので、習慣を述べる場合以外は文末は完了形（「た」形）になります。同時発生を表す文型は多くあり、「～が早いか」（→文型046）、「～なり」（→文型280）、「～とたんに」（→文型 148）や「～そばから」（→文型 127）、「～や否や」（→文型428）などですが、各項を参照してください。

　注意してほしいのは、上記の文型はどれも「～と、すぐ～」のグループで、後件で「～たい・～つもりだ・～だろう」などの意志・推量表現は使えません。これは条件を表す「と」と「たら」の違い（→資料･）から発生したものです。○　帰ったら、すぐうがいをしなさい。×　帰ると、すぐうがいをしなさい。



§　例文　§

１．ホームに着くか着かないかに、発車のベルが鳴り出した。

２．彼女は、会社から送られてきた不採用の通知を読むか読まないうちに、わっと泣き出した。

３．彼はベットに横になるかならないうちに眠ってしまった。

４．黒い雲が現れるか現れないうちに、激しい突風が吹き荒れ、その妖怪は姿を現した。

５．この店のパンは、店頭に並ぶか並ばないかのうちに、飛ぶように売れていく。



★　例題　★

1)　夜（が／を）明けるか（明ける／明けない）うちに、母は台所に立って朝御飯の支度（が始まった／を始めた）。

2)　解答を（書く→　　　　）終えるか（終える→　　　　）かのうちに、試験官の「そこまで」という声（　）　した。



(^^)前課の解答(^^)

1)　ったら（「～と言ったら」の口語→文型219）／まで／もう

2)　怒り（→文型137）／か／立ち（→文型003）



## 043 ＊～兼ねない



動詞：［ます］形　　＋　 兼ねない



♪　会話　♪

課長：李君もずいぶんと危ない賭けをやったものだ。うまくいったからいいようなものの、一歩間違ったら取り引き停止になり兼ねなかったぞ。

係長：私が商いの「いろは」から教え直します。

山田：しかし、話し方に注意しないと、誇り高い彼のことですから、辞めるなんて言い出し兼ねませんよ。



♯　解説　♭

　「～兼ねない」は不確実な推量を表す「～かもしれない」系の表現で、「（良くない事態が発生する）可能性がある」という意味を表します。「～する恐れがある」（→文型020）とほぼ同義の推量表現です。この二つは常に悪い事態にしか使えませんが、「～かもしれない」と同じく、事態の良し悪しに関係なく使える表現に「～ないとも限らない」（→文型264）があります。

　　秘密が漏れるかも知れない。

　　秘密が漏れ兼ねない。

　　秘密が漏れる恐れがある。

　　秘密が漏れないとも限らない。



§　例文　§

１．会社命令に背こうものなら、首にされ兼ねない。

２．あいつは金のためには人殺しだってやり兼ねない男だ。

３．そんなにスピードを出したら、交通事故を起こし兼ねない。

４．部下を無能呼ばわりするなんて、人を傷つけるひどい言い方だけど、あの部長なら言い兼ねないね。

５．このままでは両国の国境紛争は、全面戦争に発展し兼ねない。まさに一触即発の状態と言えるだろう。



★　例題　★

1)　旅先（に／で）は飲み水に注意しなさい。そう（する／しない）と、食あたりを（起こり／起こし）兼ねない。

2)　過ち（　）（　）学ぶことが（ない→　　　）ば、再び同じ過ちを（繰り返す→　　　　）　兼ねない。



(^^)前課の解答(^^)

1)　が（「明ける」は自Ｖ）／明けない／を始めた（自Ｖか、他Ｖか）

2)　書き／終えない／が（～がする→文型031）



## 044 ＊～兼ねる



動詞：［ます］形　　＋　 兼ねる



♪　会話　♪

李　：今回の措置は少々理解し兼ねますので、よろしければ、説明していただけないでしょうか。

課長：色々と事情があってねえ。私の口からは説明し兼ねるから、佐藤君から聞いてくれよ。

佐藤：およその事情は存じておりますが、私には説明役は少し荷が重過ぎます。



♯　解説　♭

　「～兼ねる」は「心理的・感情的理由で～できない」を意味する表現です。「～できない」を意味する可能表現は下例のように色々ありますが、各項を参照してください。下例の中で「～得ない」は「～する可能性がない」を表すので、第三者のことでないと少し不自然ですが、意味の差は別にすれば、どれも使えます。→例題2)

　お世話になった人の頼みだから、

　　断れない。

　　断り兼ねる。

　　断り得ない。　　　　　（→文型017）

　　断るわけにはいかない。（→文型457）

　　断り難い。　 （→文型034）



§　例文　§

１．あなたの意見には、どうしても賛成し兼ねます。

２．その種のことは、同僚の僕の口からは言い兼ねるね。

３．今か今かと子どもの帰りを待ち兼ねて、何度も玄関口まで見に行った。

４．彼は能力はあるが、協調性がなく、私には扱い兼ねる存在だ。

５．当館では、傘の保管には責任を負い兼ねます。各自ビニール袋に入れてお持ちください。（張り紙から）



★　例題　★

1)　たとえあなたの頼み（なら／でも）、こんな歴史を歪曲する（ように／ような）本は推薦し（得ない／兼ねる）。

2)　当店（　）いたしましては、申し訳ございませんが、その種のご相談（　）は（応じる→　　　　）兼ねます。



(^^)前課の解答(^^)

1)　で（動作の場所）／しない（→文型203）／起こし（他Ｖ）

2)　から／なけれ／繰り返し



## 045 ＊～かのようだ



名詞　　　　：　× 　／　である　 　 ＋ 　　かのようだ

動詞・形容詞：普通形＜ナ形 ー×＞



♪　会話　♪

祖父：自分の家での昔ながらの披露宴もいいもんじゃ。皆が集まると、昔に戻ったかのようじゃ。

祖母：でも裏方はもう大変。台所は盆と正月がいっしょに来たようでしたよ。

祖父：次男と末っ子にも、もう結婚相手が決まっとるかのようじゃったが、時が経つのは早いものじゃのう。



♯　解説　♭

　「～かのようだ」は「＜実際はそうではないが＞まるで～ようだ」（類似）を意味します。実際はそうではないことが暗示されているため、「～ふりをする」という意味や非難・軽蔑の感情を込めるときはこの文型がぴったりです。その際は「あたかも・さも」という副詞と結びつことが多いでしょう。例えば、「さも知っているような態度 」は「知っているふり」とほぼ同義です。なお、例文５のように「～ようだ」のかわりに古語「如し」（→文型083）が使われることもあります。



§　例文　§

１．寒いなあ。もう３月なのに、真冬に戻ったかのようだ。

２．新宿は不夜城の名にふさわしく、毎晩が祭りであるかのようににぎわっている。

３．彼女はペットの猫を、あたかも実の子であるかのように可愛がっている。

４．彼は毎日エネルギッシュで、疲れを知らないかのようだ。

５．この度の金融破綻が、全て政府・与党の無能無策から生じたかの如き主張は、我が党としては受け入れ難い。



★　例題　★

1)　（ただ／ほん）の風邪なのに、（あたかも／実に）重病人であるかの（ように／ような）大げさに騒いでいる。

2)　彼（　）きたら、さも何でも（知る→　　　　　）かのような口振り（　）話す。　＜044の例題解答＞

1)　でも／ような（～ような＋Ｎ）／兼ねる（～得ない→文型017）

2)　と（「～としては」の謙譲の形→文型237）／に／応じ



## 046 ～が早いか



動詞：原形　　＋　　が早いか



♪　会話　♪

李　：小平のしつけがなってないなあ。座るが早いか、「いただきます」も言わないで夕食に食らいついたぞ。

良子：あなたって家に帰ってくるが早いか私に小言ですか。あなたにも半分は責任があるのよ。

李　：坊主、雲行きが怪しいと思ったのか、食事が終わるが早いか逃げ出していったよ。



♯　解説　♭

　「～が早いか」は「～すると、すぐ～」を意味します。「～が早いか」は動作の同時発生を強調する点に特徴があり、以下のような自然現象や状態発生に使うと不自然になります。また、現実に起こった既定事実描写なので、後件で「～たい・～つもりだ・～だろう」などの意志・推量表現は使えません。→例題1)

　　家に帰るか帰らないうちに（？帰るが早いか）、雨が降りだした。

　　帰ったとたんに（×帰るが早いか）、涙が出てきた。

　同義表現は多くありますから、「～か～ないかのうちに」（→ 文型042）の項を参照してください。



§　例文　§

１．ベルが鳴るが早いか、彼は教室を飛び出した。

２．彼女は卒業するが早いか、結婚してしまった。

３．バスが着くが早いか、乗客は先を競って乗り込んだ。

４．主人の足音を聞くが早いか、子犬は駆け寄ってきた。

５．店が開くが早いか、お客はバーゲン会場に殺到した。



★　例題　★

1)　（まもなく／ただちに）取引先からの電話がある（はず／つもり）なので、（入ったとたんに／入り次第／入るが早いか）、（まもなく／ただちに）教えてください。

2)　隊員たちは「○○地区で火事が発生！」（　）の連絡を受けるが早いか、消防車に（乗る→　　　　）込み、現場（　）と急いだ。



(^^)前課の解答(^^)

1)　ただ（副詞の語義）／あたかも／ように

2)　と（～ときたら→文型229）／知っている／で



## 047 ＊～かもしれない／～かもわからない



名詞　　　　：　　× 　 　　　　＋　 かもしれない

動詞・形容詞：普通形＜ナ形 ー×＞ 　 かもわからない



♪　会話　♪

小平：難しいかもしれないけれど、私立の○○中学を受験してみようかと思うんだ。お母さん、いい？

良子：えっ？あの有名な○○中学？

小平：もしかしたら、合格の可能性もあるかもわからないと、先生が言ってくれたんだ。

良子：わかったわ。駄目でもともと、やってみたら？



♯　解説　♭

　「～かもしれない」は初級文型ですが、「～かもわからない」の形もあって意味も用法も変わりません。関連表現を挙げれば、可能性が高いと思えば「～だろう」、ほぼ確実だと思えば「～はずだ」が使われます。

　　明日は雨が降るかもしれない。

　　明日は雨が降るだろう（60～80％）

　　明日は雨が降るはずだ（95～99％）

　以上は知的推量に属しますが、人間の五感に基づいて感覚的に推量するときは「～ようだ／～そうだ／～らしい」（→資料｢）が使われます。例えば、人の額に触って「熱があるようだ」とは言っても、「熱があるだろう」とは言えません。



§　例文　§

１．帰りが遅すぎる。娘の身に何かあったのかもしれない。

２．そう言えば、そんなことを言ったかもしれないなあ。

３．ずいぶん勝手な奴だとお思いになるかもしれませんが、先日の話は一旦白紙に戻していただけないでしょうか。

４．一時父は重体で、もう助からないかもしれないと思ったが、どうやら峠は越したようだ。

５．ひょっとしたら、行方不明の息子が帰ってくるかもしれないと思って、部屋はそのままにしてあるんです。



★　例題　★

1)　机上の理論（として／にとって）は成立する（はずだ／かもしれない）が、現実から（は／が）遊離した空論だ。

2)　旅先（　）何があるかもわからないから、その際はここ（　）電話を（入れる→　　　　　）なさい。



(^^)前課の解答(^^)

1)　まもなく／はず（→文型367）／入り次第（→文型111）／ただちに

2)　と（内容の引用）／乗り（→文型094）／へ（～へと→文型387）



## 048 ～からある／～からする／～からの



数詞：　×　　＋　　からある　　　　　　　　　　からする　　　　　　　　　　からの　＋　名詞



♪　会話　♪

山田：例の他社から引き抜かれて来た彼、懸案だった○○物産を見事に開拓しちゃったよ。やはり凄腕だよ。

李　：「営業の鬼」と言われる人物だけあるねえ。今まで10人からの営業が当たっても無理だったのにねえ。

山田：その報賞として、社長から金一封と50万円からする時計をもらったそうだ。



♯　解説　♭

　これらの文型の用法は「～を越える～」「～以上ある～」という意味を表します。話者とって数量がとても多いと感じられるとき使われる文型で、距離・重量・高さなどには「～からある」、金額には「～からする」、人数には「～からの人」が使われます。

　例えば実際は二万円でも、その数量をどう感じるかで表現は異なります。

　　二万円ぽっちの時計　＜その時計をとても安いと感じている＞

　　二万円しかない時計　＜その時計を安いと感じている＞

　　二万円ばかりする時計＜その時計を少し高いと感じている＞

　　二万円からする時計　＜その時計をとても高いと感じている＞



§　例文　§

１．彼は50キロからあるバーベルを軽々と持ち上げた。

２．この骨董品は明代の物で、買うとなると50万円からします。

３．この前の地震では、二万人からの人々が家を失い、五千人からの人が死にました。

４．この湖は、深いところは三百メートルからあります。

５．数名しか採用しない会社の社員募集に、五百人からの人が応募した。



★　例題　★

1)　二億円から（ある／する）絵画をぽんと買っていく（なんか／なんて）、一体どんな人なん（だい／かい）？

2)　日本人が中学まで（　）習う教育漢字だけで881字からある。非漢字圏の学生たちから、とても（覚える→　　　）切れないという悲鳴（　）聞こえてくる。



(^^)前課の解答(^^)

1)　として（→文型237）／かもしれない／は

2)　で／に（「へ」も可）／入れ（Ｖ〔ます〕形＋なさい）



## 049 ＊～から言うと／＊～から言えば／＊～から言って



名詞：　×　　　＋　　から言うと

　　　　　　　　　　　から言えば

　　　　　　　　　　　から言って



♪　会話　♪

李　：営業担当として言わせていただくと、新製品の開発はできるだけ急いでいただきたいです。

佐藤：今一歩のところまで来てはいるんですが、現状から言って、もう一ヶ月程度はみてください。

課長：他社に先を越されては困るし、かといって品質に問題があっても困る。とにかく、部長の指示を仰ごう。



♯　解説　♭

　「～から言うと／＊～から言えば／＊～から言って」は「～ の観点から判断して言えば ～」という意味で、用法の差はありませんが、仮定の「と／ば」がないため、「～から言って」は断定に近い語感になります。

　同義表現に「～から見ると／～から見れば／～から見て／～から見たら」（→文型059）、「～からすると／～からすれば／～からして」（→文型052）がありますから、各項を参照してください。



§　例文　§

１．A社の製品は、デザインから言えばB社に勝るが、実用性から言えば劣っている。

２．彼の性格から言って、その程度のことでくよくよしたりしないでしょう。

３．健康という観点から言えば、激しい運動は「百害あって一利なし」です。

４．この成績から言うと、○○大学は少し無理かと思う。

５．交渉の進展状況から言って、今夜が山場になるだろう。



★　例題　★

1)　親の気持ち（から言えば／からと言って）、血を分けた自分の子供（ほど／しか）大切なもの（は／が）ない。

2)　気候（　）（　）言うと、北海道の方（　）北京より寒いんじゃない（　）と思える。



(^^)前課の解答(^^)

1)　する／なんて（→文型274）／だい（→文型129）

2)　に（→文型402）／覚え（～切る→文型067）／が（自Ｖ）



## 050 ＊～からこそ／～ばこそ



名詞　　　　：　だ／である　　　　　　　　　＋　　からこそ

動詞・形容詞：普通形＜ナ形ーだ／である＞

名詞　　　　：　であれば／なら　　　　　　　＋　　こそ

動詞・形容詞：仮定形＜ナ形ーであれば／なら＞



♪　会話　♪

良子：心配してると思えばこそ、こうして電話してるのに、いきなり怒鳴りつけることもないでしょ。

李　：一体全体、今何時だと思ってるんだ。帰りが遅すぎるから、何かあったのかと心配してたんだぞ。

良子：それにしても、もう少し優しく話してくれたっていいんじゃないの？



♯　解説　♭

　「～からこそ／～ばこそ」は、どちらも「正に～だから～」と原因・理由を強調する表現です。副助詞「こそ」と結びついて、文末が「～んです」と呼応するのが特徴です。「～からこそ」と「～＜仮定形＞ばこそ」の多くは置き換え可能ですが、仮定形の「～ば」は文末に完了形（「た」形）がとれない制約があるため、例文４、５のような場合は不自然になります。

　君が来いと　○言ったからこそ　僕は来たんだ。

　　　　　　　×言えばこそ



§　例文　§

１．親は子を愛するからこそ、厳しくしかることもある。

２．健康だからこそ、幸せな日々が過ごせるのよ。

３．君のことを心配すればこそ、注意しているんです。

４．この作品は、妻の協力があったからこそ完成したのです。

５．私の話に耳を貸さなかったからこそ、失敗したんだ。こうなっては、もう取り返しがつかない。



★　例題　★

1)　苦し（さ／み）が多いほど、また喜びも大きい。そして、悲し（さ／み）が多いほど、人に優しくなれる。このように人生は、表裏一体だ（からこそ／からには）おもしろいんじゃないか。

2)　希望が（ある→　　　　）ばこそ、人は（生きる→　　　　　　　）いけるんじゃないでしょう（　）。



(^^)前課の解答(^^)

1)　から言えば／ほど／は

2)　から／が／か



## 051 ＊～からして



名詞：　×　　＋　からして



♪　会話　♪

李　：今度の新入社員、どうなってるんだ。お辞儀の仕方からして、まったくなってないよ。

山田：ぎこちないくらいだと可愛いんだけど・・・。それに身なりからして堅気の会社員には見えないな。

課長：彼らは君たちにない何かを持っているんだから、一日も早く戦力化する方法を考えようや。



♯　解説　♭

　「～からして」は主に例文１、2のように「～をはじめとして、その他はもちろん～」という意味を表しますが、「～をはじめとして」（→文型474）の強調と考えていいでしょう。それ以外にも例文３のように「から」の強調として使われます。また、例文４、５のように「～から判断して」を意味することもありますが、その場合は、次項の「～からすると／～からすれば」（→文型052）と同義表現になります。＜≒をはじめとして＞

　　Ａ国は食料からして欠乏状態だから、衣類・燃料も欠乏しているに違いな

　　い。＜≒から判断して＞　

　　Ａ国の深刻な食糧事情からして、衣類・燃料も欠乏しているに違いない。



§　例文　§

１．金持ちというのは、靴からして我々庶民の物とは違うね。

２．あいつは言葉遣いからして生意気だ。

３．天才というのは、もう生まれたときからして凡人とは違っているらしい。

４．最近の株価の動きからして、景気は上向いていると言えるでしょう。

５．あの先生、顔つきからして恐そうねえ。



★　例題　★

1)　一流モデル（ともなると／ともすると）、歩き方（と／や）身のこなし方（からして／からすれば）、（どこが／どこか）普通の人と違って優雅だ。

2)　先日会った老人は、その身なりや上品（　）言葉遣い（　）（　）して、一角の人物だ（　）すぐわかりました。



(^^)前課の解答(^^)

1)　み（→文型097）／み／からこそ

2)　あれ／生きて（～ていく→文型177）／か



## 052 ＊～からすると／＊～からすれば



名詞：　×　　＋　からすると

　　　　　　　　　からすれば



♪　会話　♪

佐藤：この一泊二日の職場旅行のプラン、どう思う？僕にしてみれば、ずいぶん思い切って張り込んだんだけど。

百恵：温泉というのはありふれてるんじゃない？

李　：正直に言わせてもらうけど、この値段からすると中身も余り期待できないんじゃないかなあ。

佐藤：何もかもうまくいく案なんてないよ。



♯　解説　♭

　これらの文型は「～から判断すると～」という意味を表す表現で、この「する」には「見る・言う・考える」などの多くの語義が含まれています。なお、以下はほぼ同義表現です。

　この成績から

　　　すると／すれば／して

　　　言うと／言えば／言って（→文型049）

　　　見ると／見れば／見て　（→文型059）

　合格は間違いないと思う。



§　例文　§

１．儲けしか考えない企業は、長期的な観点からすると、将来性はありませんねえ。

２．わが家の経済状態からすると、家を買うのは夢のまた夢だ。

３．法律的見地からすれば責任はなくても、道義的責任は免れない。

４．男からすれば、家族のために働いているのに、妻から粗大ゴミ扱いされたのではたまらないよ。

５．妻の立場からすれば、そう考えるのは当然でしょうね。



★　例題　★

1）　今年の天候（からして／からこそ）、小豆の収穫はあまり期待（できる／でき）（そうではない／そうもない）。

2）　患者の立場からすると、薬の成分は何（　）、副作用はどう（　）、無関心では（いられる→　　　　　　　）。



(^^)前課の解答(^^)

1)　ともなると（→文型253）／や／からして／どこか

2)　な（ナ形）／から／と（内容を示す「～と」）



## 053 ＊～からと言って／＊～からって／～からとて



名詞　　　　：　　　　だ　　　　　＋　からと言って ～ ない

動詞・形容詞:：普通形＜ナ形ーだ＞　　　からって

　　　　　　　　　　　　　　　　　　　からとて



♪　会話　♪

李　：景気がいくらいいからと言って、何もしなくても自然に物が売れるってわけじゃあないよ。

山田：でも店の前でやたらに呼び込みをしたからって、お客が来てくれるとは限らないよ。

課長：しかし、客足が少ないからと言って、むざむざと店をたたむわけにはいかないからなあ。



♯　解説　♭

　これらの文型は「いくら～（の）理由があったとしても～」という意味を表します。「～からと言って」の短い形が「～からって」で、文語が「～からとて」ですが、意味・用法は同じです。これらの文型はどれも「～ても」で置き換えることが可能ですが、この文型は文末に否定判断を加えるのが特徴で、多くは「～からと言って～ない」と呼応します。

　　熱が 熱が下がっても（≒ 下がったからと言って）、安心してはいけない。

　　誰が反対しても（×反対したからと言って）、私は行く。



§　例文　§

１．日本人だからと言って、正しく敬語が使えるとは限らない。

２．相手が弱そうに見えるからって、決して油断するな。

３．苦しいからとて、途中で投げ出すわけにはいかない。

４．健康に自信があるからって、そんなに無理をしてると体を壊しますよ。

５．夫婦だからと言って、お互いに何の秘密もないなどということはあり得ませんよ。



§　例題　§

1）　ボーナスが出た（からには／からと言って）、無駄遣いをするな。社会人になった（からには／からといって）、いざというの時のための蓄えをし（ておけ／てしまえ）。2）　一度（　）二度、受験に（失敗する→　　　　　）からって、（しょげる→　　　）込むことはないよ。



(^^)前課の解答(^^)

1)　からして／でき／そうもない（様態「そうだ」の否定形に注意）

2)　か／か／いられない（～てはいられない：→191Ｐ）



## 054 ～から成る



名詞：　×　　＋　 から成る



♪　会話　♪

課長：今日の慰労会には、各地の販売代理店の社長などの幹部から成る方々がお集まりだ。

山田：八時からカラオケ大会が予定されていますが、会場設定の事前チェックが必要ですね。

李　：でも、百人からの団体となると、まとまりがつかなくなりそうで、何かと気を使いますね。



♯　解説　♭

　「～から成る」は「～は～ の（要素・部分・材料）からできている」という意味を表す表現です。類形文型に「～からある」（→文型048）があり、混同しやすいので注意しましょう。

　　当校のサッカーチームは20人の部員から成る（×からある）。

　　試験まで、まだ10日からある（×から成る）。



§　例文　§

１．水は水素と酸素から成る。

２．この全集は、全部で五巻から成っている。

３．大小五十の島々から成るこの○○諸島は、美しい珊瑚礁でも有名である。

４．日本の国会は、衆議院と参議院から成り、国会は国の最高決定機関である。

５．今回の訪米使節団は、総勢20名の国会議員と経済界代表から成っている。



★　例題　★

1）　仏教（によって／によると）、人間の欲望は108の煩悩 （からなる／からある）と（言っている／言われている）。

2）　その草野球チームは、同じ地域（　）住む様々（　）職業の人たち（　）（　）成っていた。



(^^)前課の解答(^^)

1)　からと言って／からには（→文型056）／ておけ

2)　や／失敗した／しょげ（～込む→文型094）



## 055 ＊～から～にかけて／＊～から～にかけ



名詞・数詞：×　　＋　　から

名詞・数詞：×　　＋　　にかけて

　　　　　　　　　　　　にかけての　＋　名詞

　　　　　　　　　　　　にかけ



♪　会話　♪

李　：夜半から明け方にかけて風が強かったけど、君、気がついたかい？

良子：雨もどしゃ降りだったらしくて、台所から居間にかけてびしょ濡れよ。

李　：それで濡れたタオルが、何枚も外の物干しにかけてあるんだね。



♯　解説　♭

　「～から～にかけて」は「～から～まで」のグループで、時・場所・空間を表す名詞と結びついて、「～から ～まで、ずっと～」を意味する表現です。

　類似表現に「～から～にわたって」（→文型057）がありますが、日時・場所の起点と終点を特定し、その継続性を強調するときは「～から～にかけて」が使われ、「～から～にわたって」は使えません。逆に、○ヶ月・○年・○週間・○日間のように期間を述べるときは「～から～にわたって」が使われ、「～から～にかけて」が使えません。→ 例題1)

　　今月の十日から二十日にかけて（×にわたって）、研究会が開かれた。

　　今月の十日から十日間にわたって（×にかけて）、研究会が開かれた。



§　例文　§

１．六月から七月にかけて、日本は梅雨のシーズンです。

２．名古屋から大阪にかけて、高速道路は百キロ以上にわたる大渋滞が続いています。

３．日本では年末から正月にかけて、ＪＲも飛行機も帰省ラッシュになります。

４．金曜日から日曜日にかけて、新宿の夜はにぎわいます。

５．額から眉にかけて、三日月形の刀傷がある。



★　例題　★

1）　中央線は、（たった今／ただ今）、新宿駅から中野駅（にわたって／にかけて）、信号故障の（ために／せいで／おかげで）不通となっております。

2）　私は中学（　）（　）高校（　）かけて、甲子園（　）目指して、野球（　）熱中していました。



(^^)前課の解答(^^)

1)　によると（→文型350）／からなる／言われている（→文型221）

2)　に／な（漢語形容詞はナ形）／から



## 056 ＊～からには／＊～からは



名詞　　　　：　　　である　　　　　　　＋　　からには

動詞・形容詞：普通形＜ナ形ーである＞ 　　　　 からは



♪　会話　♪

課長：この仕事、わが課が引き受けたからには、立派にやり遂げたいと思う。なんだか闘志が湧いてきたぞ。

李　：課の名誉がかかっているからには、万が一にも失敗は許されませんね。

山田：不肖、私が助っ人に来たからはご安心ください。

李　：やけに大口をたたくねえ。お前が一番心配なんだよ。



♯　解説　♭

　「～からには／～からは」は「～だから、当然／必ず ～」という意味を表す「から」系の原因・理由表現で、文末には「～なければならない」や「～べきだ」（→文型382）、「～つもりだ」や「～たい」などの義務や意志・希望の表現、「～はずだ」（→文型367）や「～にちがいない」（→文型305）などの断定判断が多く現れます。この文型は、「～以上」（→文009）や「上は」（→文型015）と同義表現となります。

　 原因・理由の表現には「から」系、「ので」系、「て」系があります。大きく分ければ、「から」系は未定・未来・意志表現に、「ので」系は既定や過去表現に、「て」系は形容詞や状態の自然発生に使われます。詳しくは「資料､」を参照してください。



§　例文　§

１．こんなに安いからには、きっと偽物に違いないよ。

２．共同生活をするからには、そこには最低限の規則が必要となる。

３．誰だって闘うからには勝ちたいと思う。それは人情だ。

４．こうなったからには、もう、運を天に任せて、捨て身でぶつかるしかない。

５．彼があんなに自信を持って断言するからには、何か根拠があるんだと思う。



★　例題　★

1）　そこ（ほど／まで）言う（からこそ／からには）、私が犯人だという証拠があって（の／×）ことなんだろうねえ。

2）　君（　）我々の秘密を知られた（　）（　）には、気の毒だが、生かしておく（　）（　）にはいかない。



(^^)前課の解答(^^)

1)　ただ今／にかけて／ために（客観的に理由伝えるときは「ために」）

2)　から／に／を（→文型479）／に（対象）



## 057 ＊（～から）～にわたって／＊（～から）～にわたる



名詞・数詞： ×　　＋　　から

名詞・数詞： ×　　＋　　にわたって

　　　　　　　　　　　　　にわたり

　　　　　　　　　　　　　にわたる ＋ 名詞



♪　会話　♪

部長：今朝の経営会議で、社長から直々に新製品計画の詳細にわたる説明があった。

李　：説明は新製品の商品企画から補修計画にまでわたったのですか？

部長：うん、三時間にもなって、社長もお疲れのようだった。不謹慎なようだが、聞いてる方も疲れたよ。



♯　解説　♭

　「（～から）～にわたって」は期間・場所・空間を表す名詞や数量を表す語について、その「（～から～までの）およその範囲内で」を表します。類義表現である「～から～にかけて」（→文型055）との用法の違いを簡単に言えば、「～から～にかけて」は＜線＞、「～から～にわたって」は＜面＞の感覚です。この文型は起点を明示しないで、単独で「～にわたって／～にわたり」と使われることも多く、現象や動作が時間・空間の範囲全体に広がっている語感をもっています。名詞を修飾するときは「～にわたる＋名詞」の形を取ります。



§　例文　§

１．九州地方から四国地方にわたって、暴風雨に見舞われ、 多くの家屋が倒壊した。

２．十年にわたる内戦に次ぐ内戦で、国土は荒れ果てた。

３．長年にわたる経験のなかから生まれた知恵は、学問的知識に勝ることもある。

４．日本と大陸の間には二千年にわたる交流の歴史がある。

５．その腎臓移植手術は、六時間にわたる大手術となった。



★　例題　★

1）　ただ今、関東南部一帯（にかけて／にわたって）、震度五の地震が（あります／ありました）。沿海部では津波の（嫌い／恐れ）もありますから、御注意ください。

2）　この問題は延べ十回（　）わたって議論された（　）、結論には（至った→　　　　　　）。



(^^)前課の解答(^^)

1)　まで（形に注意：「それほど」「そこまで」）／からには／の

2)　に（受身文）／から／わけ（→文型457）



## 058 ＊～から～に至るまで



名詞・数詞：　×　　＋ 　　から

名詞・数詞：　×　　＋　　 に至るまで

　　　　　　　　　　　　　 に至るまでの ＋ 名詞



♪　会話　♪

山田：彼は面倒見がいいね。帰国者のために、住む所から働き口の世話に至るまで至れり尽くせりだ。

佐藤：その中国帰国者のグループは、男性ばかりでなく女性も混じっていて、年齢も子供から老人までだろ。

山田：うん。あれじゃあ、朝早くから夜中まで、のんびり休める暇なんてないんじゃないかな。



♯　解説　♭

　「～から～に至るまで」は「～から～まで、例外なく全て」という意味を表す表現です。「～から～まで」の文は起点と終点を示すだけですが、「～から～ に至るまで」は、その間に含まれる物や事、時間や場所などが、例外なく全てそうだという点に、話者の重点が置かれています。→例題1) 　ですから、下例のように「例外なく全て」を強調する必要がない用例に使うと不自然になります。

　　「会社は何時から何時まで（×に至るまで）ですか」

　→「九時から五時まで（×に至るまで）です」



§　例文　§

１．「赤トンボ」は大人から子供に至るまで、日本人なら誰でも知っている歌です。

２．当社は設計から施工に至るまで、一切をお引き受けいたします。

３．借金の額に至るまで、根ほり葉ほり聞かれた。

４．「出会いから新婚旅行に至るまで」、これがわが結婚相談所のモットーです。

５．先の戦争は開戦から敗戦に至るまで、多くの謎が存在する。



★　例題　★

1）　幼児期から老年期（まで／に至るまで）の生涯教育という観点が、最近（になって／にして）注目（して／されて）きた。

2）　この旅館は、細部に至る（　）（　）、心（　）こもっていて、サービスが（行き届く→　　　　　　）。



(^^)前課の解答(^^)

1)　にわたって／ありました／恐れ（→文型020／→文型063）

2)　に／が（逆説）／至らなかった



## 059 ＊～から見ると／＊～から見れば／＊～から見て



名詞：　×　　＋　　から見ると

　　　　　　　　　　から見たら

　　　　　　　　　　から見れば

　　　　　　　　　　から見て



♪　会話　♪

部長：私の目から見ても素晴らしい製品だ。開発担当の諸君には、これまで本当に苦労をかけた。

李　：価格性能比から見ると確かに画期的ですが、製造面から見たらどうなんでしょうね。

部長：工場長の表情から見ると、決して楽観できなさそうだよ。この製品は正に新技術の固まりだ。



♯　解説　♭

　これらの文型は「～から見て判断すると」という意味を表す表現で、「～から言うと／～から言えば／～から言って」（→文型049）、「～からすると／～からすれば」（→文型052）と同義表現です。視覚判断や、他の意見・評価と比較・対比が強調されることが特徴と言えるでしょう。



§　例文　§

１．子供の頃から見ると、世の中、ずいぶん豊かになったものだ。

２．卒業当時から見たら、格段に会話力が進歩したね。

３．大人の目から見ればくだらないと思える物も、子供には宝物だったりする。

４．動物たちから見れば、人間ほど残酷な生き物はいないだろうよ。

５．外見から見て、まともな職業に就いている人とは思えませんでした。



★　例題　★

1）　国民の目（によると／から見ると）、政策不在の権力争い（ほど／しか／だけ）情けないもの（は／が）ない。

2）　漢字は、その（作られる→　　　　　）方と性質から見て、（大きい→　　）六つ（　）分けられます。



(^^)前課の解答(^^)

1)　に至るまで（△まで）／になって／されて（受身形）

2)　まで／の（「が」も可）／行き届いている（辞書形は未来）



## 060 ＊～ かわりに



名詞　　　　：　　　　の　 　　　　＋ 　　かわりに

動詞・形容詞：普通形＜ナ形ーな＞



♪　会話　♪

小孫：頑張ってるのに日本語が上達しなくて・・・。

良子：あの有名な兎と亀のかけっこの話を知ってる？

小孫：兎が高をくくって、途中で昼寝してしまい、亀に追い越されたっていうあの話？

良子：あなたは進歩が遅いかもしれないけど、そのかわりに着実さがあるわ。それがあなたの大きな取り柄だわ。



♯　解説　♭

　「かわる」は漢字で「換わる／替わる／代わる／変わる」と書くように多義語です。「～ かわりに」の用法は大きく分けて、例文１の「～の代理に」、例文２の「～の代理・代替に」、例文３、４の「～けれども」、例文５の「～交換・代償に」という四つの意味に分かれます。どの意味で使われているかは、文脈から理解する以外にありません。この中で注意するのは、交替から対比へと意味が拡大した「ＡけれどもＢ」という逆説の表現でしょう。

　なお、例文１の代理の用法の時には「名詞＋にかわって」（→文型303）の形も使えます。

　　社長にかわって（・のかわりに）、専務が出席することになった。



§　例文　§

１．この仕事は君の方が適任だ。僕のかわりに君がやってくれないだろうか。

２．「戦時中はご飯のかわりにさつまいもを食べた」という話を母から聞いたことがある。

３．このアパートは駅に近くて便利なかわりに、家賃が高いのが玉に瑕だ。

４．この種の商売は儲けも大きいかわりに、リスクも大きい。

５．先日おごってもらったかわりに、今日は僕がおごるよ。



★　例題　★

1）　僕が日本語を教え（てあげる／てくれる）（かわりに／にかわって）、君が中国語を教えて（あげないか／くれないか）。

2）　この車はガソリン（　）食わないかわり（　）、スピー　ド（　）出ない（　）が難点だ。



(^^)前課の解答(^^)

1)　から見ると／ほど／は（～ほど～はない→395Ｐ）

2)　作られ（方法）／大きく／に（「～を～に分ける」の受身文）



## 061 ～きっての



名詞（集団・組織を表すもの）： ×　　＋　きっての　＋　名詞



♪　会話　♪

李　：日本きっての名勝古跡というと、どこかなあ。

良子：難しい質問だけど、私なら京都の嵐山を挙げるわ。

李　：あそこもいいけど、奈良のひなびた雰囲気も捨てられないなあ。

良子：人によって好きなところは違うってことね。近くでは箱根が一番好きよ。



♯　解説　♭

　「きっての」は「～の範囲内で最も優れている」という意味を表します。前に来る語は組織・団体などの名称です。これは最上級を表す比較文型の一種でしから、「この町きっての物知り＝この町で一番の物知り」のように「～の中で、一番の～」を使っても表せます。



§　例文　§

１．○○先生は当代きっての日本画家としての誉れが高い。

２．何と言っても、彼女はわが校きっての秀才と言えるだろう。

３．彼はこの町きっての人気者で、何か催し物があると引っ張りだこだ。

４．専務は会社きっての切れ者と噂されている。

５．わが社きっての歌自慢と言えば、李君をおいてほかにいないだろう。



★　例題　★

1）　村（あっての／きっての）力自慢だったが、東京に来（てみると／てみれば）、上には上がある（のだ／ものだ）と思い知らされた

2）　彼はこの会社きって（　）中国通という評判だ（　）、果たして本当なん（だ→　　　　　）か。



(^^)前課の解答(^^)

1)　てあげる／かわりに（交換・代償）／くれないか（→文型182）

2)　を（他Ｖ）／に／が（自Ｖ）／の（→文型354）



## 062 ＊～ 気味



名詞：　×　　　　＋　　気味だ

動詞：［ます］形　　　　 気味で

　　　　　　　　　　　　気味の　＋　名詞



♪　会話　♪

小孫：大学入試が近づいているのに、少しも勉強が進まないんだ。それに全然自信が持てないし・・・。

良子：少々、焦り気味のようねえ。そんな時は思い切って山にでも行って、気晴らしした方がいいわよ。

小孫：そんな心境にはとてもなれないよ。それにこの数日、風邪気味で冴えないし・・・。



♯　解説　♭

　「気味」は「気味の悪い男が、家の周りをうろうろしている」のように、元々嫌な感触や感情を表す語です。

　「～気味」はそれが接尾語化したもので、「（体や心に）少し～と感じる状態」という意味を表しますが、「風邪気味・疲れ気味・下がり気味・上がり気味・遅れ気味…」など、不満やよくないと評価する気持ちを込めて使わる場合がほとんどです。

　注意してほしいのは、「疲れがち・下がりがち…」などの類義文型の「～がち」（→文型037）との違いですが、「～がち」は「～する回数や傾向が多い」という意味ですから、用法に違いが生じます。→例題1)



§　例文　§

１．就職してからは、運動不足のせいか、少し肥り気味だ。

２．ちょっとやせ気味で、目つきの鋭い男でした。

３．彼女は離婚してから、少しヒステリー気味です。

４．どうも工事の進行が遅れ気味だ。もっと現場にハッパをかけてくれ。

５．一時は飛ぶ鳥を落とす勢いだったが、最近、Ａ歌手の人気も下がり気味だねえ。



★　例題　★

1）　納期に（迫り／迫られ）と、休日（だけ／すら）返上して働いているので、工員達は疲れ（気味／がち）です。

2）　君は少し（うぬぼれる→　　　　　　）気味じゃないか。本当の（強い→　　）とは、自分を拠り所に（する→　　　）ながら、うぬぼれでない自信をもつことだよ。



(^^)前課の解答(^^)

1)　きっての／てみると（過去文では「と」）／ものだ（→文型420）

2)　の／が（逆説）／だろうか（→文型161）



## 063 ～嫌いがある



名詞：　　の 　 　　＋　嫌いがある

動詞：原形／ない形



♪　会話　♪

李　：深刻な顔して、何を考え込んでいるんだい？

良子：妹にいい就職先が見つかるかどうか心配で・・・。

李　：まだ、五月だよ。一年も先の事じゃないか。「来年のことを言うと鬼が笑う」ってさ。

良子：あなたは現実を甘く見る嫌いがあるわね。もう会社まわりしてるクラスメートもいるのよ。



♯　解説　♭

　「～嫌いがある」は「～という良くない傾向がある」という意味を表します。ほとんどは人が主語の文ですが、仮にもの・ことが主語になるときも背後に人の責任が存在している場合に使われます。ですから自然現象や、単に回数が多いことを表すときは使われません。その点、同義語に「～がちだ」（→文型037）は、回数・傾向・自然現象まで広範に使えます。どちらも「ともすれば／よく／しばしば」などの副詞と呼応することが多いので、一緒に覚えておきましょう。→例題1)

　　年の暮れは交通事故が多発しがちだ（・多発する嫌いがある）。

　　明日の天気は曇りがちになる（×曇る嫌いがある）。



§　例文　§

１．この消費社会は、物を使い捨てにする嫌いがある。

２．彼は協調性はあるが、決断力に欠ける嫌いがある。

３．最近の小説は、内容が浅薄な嫌いがある。（「ナ形」の例）

４．どうも彼は結論だけ言って、丁寧に説明しようとしない嫌いがあるようだ。

５．若者は、その理想主義から、ともすれば過激な行動に走る嫌いがある。



★　例題　★

1）　君は（もしかすると／ともすると）、独断専行に走り（がちだ／嫌いがある）から、もっと周りに気を配る（ように／みたいに）心がけた方がいい。

2）　日本の企業（　）は学歴偏重（　）嫌いがあるが、これでは国際競争に（生き残れる→　　　　　　）まい。



(^^)前課の解答(^^)

1)　迫られ（受身）／すら（→文型100）／気味（～がち：→文型037）

2)　うぬぼれ／強さ（→文型097）／し（～ながら：→文型270）



## 064 ＊～ きりだ／＊～きり～ない



名詞・これ・それ・あれ：　×　　＋　　(っ)きりだ

動詞　　　　　　　　　：た形　　　　　(っ)きり　～　ない

　　　　　　　　　　　　　　　　　　　(っ)きりで　～　ない



♪　会話　♪

李　：給料日の前は辛いよ。二千円しか残っていないから、寝て暮らすしかないよ。

良子：あっ、思い出したわ！この前の二万円貸したきりで、まだ返してもらってないわ。

李　：しまった！口は災いの元だ。

良子：「後悔先にたたず」ということわざもあるわ。



♯　解説　♭

　「～きりだ」は名詞・数量、或いは「こ・そ・あ」について、「～だけだ」と同じ意味を表しますが、「非常に僅かだ／とても不足している」といった話者の感情が強調されます。また、動詞の完了形と結びついて「～したきり～ない」という文型を作りますが、「～したのが最後で、その後、ずっと～ない」という意味を表します。この表現は「～したまま～ない」と「まま」（→文型406）を使っても表せますが、「まま」は「～の状態を変えない」という意味ですから、不安や心配や失望の感情は「～したきり～ない」の方が強く現れますし、例文によっては「きり」と「まま」の意味の違いが用法の違いとして現れる場合もあります。→例題1)



§　例文　§

１．歳をとって、ひとりっきりで暮らすのは心細いものです。自分しか頼れる者がいませんからねえ。

２．今日は特別に許しますが、これっきりですよ。

３．張君はアメリカに行ったきり、何の音沙汰もなくなった。

４．張先生とは、五年前にお会いしたきりです。

５．彼に声をかけたが、ふんとそっぽを向いたきり、見向きもしなかった。



★　例題　★

1）　その報告書には（じっと／ざっと）目を通した（きり／まま）で、細かい内容（まで／だけ／しか）はよく覚えていません。

2）　彼女は（うつむく→　　　　　）きり、何を尋ねても一言（　）口を（きく→　　　　）とはしなかった。



(^^)前課の解答(^^)

1)　ともすると／がち（Ｖます形＋）／ように（～みたいだ→文型408）

2)　に／の／生き残れ（一段動詞＋まい→文型398）



## 065 ～ きりしか～ない／～だけしか～ない



名詞（＋格助詞　：　×　　＋　　きりしか　～　ない

これ・それ・あれ：　×　　　　　だけしか　～　ない

数詞　　　　　　：　×　　　　　　　　　　　　　　　

　　　　　　　　　



♪　会話　♪

李　：すまんが、給料日まで一万円ほど貸してもらえないかなあ。恩にきるから。

良子：またなの？返せるめどがあるの？やはり、私が財布の紐を握ってて正解だったわ。待ってて。あっ！５千円きりしか残っていないわ。

李　：あ～あ、いつもわが家は火の車か。



♯　解説　♭

　「きり」は名詞や数詞、また「こ・そ・あ」と結びついたとき、「だけ」と同じ意味を表しますが、この「きり」「だけ」が「～しか～ない」と結びついたのがこの文型で、限定を表します。話者の「非常に僅かだ／とても不足している」という感情を一層強調する「～しか～ない」と考えていいでしょう。

　　500円しかない。

　　500円だけしかない。

　　500円きりしかない。



§　例文　§

１．僕の手元には、お金はこれだけしかありません。

２．まだその本は見出しだけしか読んでいないから、感想まではちょっと・・・。

３．彼とは一度きりしか会ったことがないんです。

４．田中角栄は小学校きりしか出ていないが、総理大臣にまで上り詰めた。

５．僕は絵を描くことだけしか能がない男ですが、絵は僕にとって命です。



★　例題　★

1）　その件は彼（だけ／にだけ）しか話さなかったはずな（ので／のに）、なぜ君が知っている（んだい／かい）？

2）　今日、学校（　）は僕きりしか（来ている→　　　　　）けど、まさか休校（　）んじゃないだろうなあ。



(^^)前課の解答(^^)

1)　ざっと／きり（～まま→文型406）／まで（→文型403）

2)　うつむいた／も／きこう（→文型441）



## 066 ぎりぎり／すれすれ



名詞：　×　　＋　　　ぎりぎり

　　　　　　　　　　　すれすれ



♪　会話　♪

小孫：辛うじて日本語能力試験一級に合格できました。

李　：おめでとう。で、何点だったの？

小孫：あのう、281点です。

李　：合格点ぎりぎりだね。でも、何はともあれよかった。

小孫：でも、僕のクラスには合格点すれすれの279点で涙を飲んだクラスメートがいるんです。



♯　解説　♭

　「ぎりぎり」は例文1のように「境界線や限界」、「すれすれ」は「境界線や限界にとても近いところ」を表す語ですが、同時に名詞に直接つく接尾語の用法をもっています。どちらも置き換えられる例が多いのですが、意味上の違いから、下の例のように用法の違いが生じることがあります。それは、「すれすれ」は境界線に接触していないからです。

　　発車時間すれすれに（・ぎりぎりに）駅に着いた。

　　鴎が海面すれすれに（×ぎりぎりに）飛ぶ。



§　例文　§

１．これが譲歩できるギリギリの線です。これ以上は無理です。

２．その川下りの遊覧船は岩すれすれのところを通り、実にスリル満点だった。

３．僕の体すれすれ（×ぎりぎり）のところを車が走り去った。

４．みんなやきもきしているのに、待ち合わせ時間ぎりぎり（？すれすれ）になっても、彼は姿を現さなかった。

５．入学願書の提出の締め切り日ぎりぎり（⇔すれすれ）になっても、彼はまだ願書を書き上げていなかった。



★　例題　★

1）　昨夜の大雨（で／に）川の水（が／を）増水し、道路（すれすれ／そこそこ）に（さえ／まで）達している。

2）　試験の開始時間ぎりぎり（　）なって、彼は試験会場（　）（駆ける→　）込んできた。



(^^)前課の解答(^^)

1)　にだけ／のに（理由の逆説）／んだい（→文型129）

2)　に／来ていない／な



## 067 ＊～ 切る／＊～切れる／＊～切れない



動詞：［ます］形　　＋　　切る

　　　　　　　　　　　　 切れる

　　　　　　　　　　　　 切れない



♪　会話　♪

山田：あ～あ、やっぱりふられちゃった。でも、彼女のこと、諦め切れないなあ。

佐藤：一度や二度の失恋が何だって言うんだよ。自慢じゃないが、俺なんて失恋歴五回だぞ。

山田：それで悟り切った顔をしてるんだ。

佐藤：おい、それって俺を褒めたつもりかい？



♯　解説　♭

　「～切る」は元々「噛み切る・叩き切る・焼き切る…」のように切断を意味していますが、終わらせる行為、更に「完全に～する」という意味が派生します。他動詞や「人」が主語になる自動詞（例：走る・歩く・勝つ…）など、動作性動詞につくと行為の完了・完遂を表します。

　　ビールを一気に飲みきった。

　　ゴールまで走りきった。

　状態性の自動詞や「あきらめる・苦しめる・信じる・軽蔑する…」などの感情・心理を表す動詞につくと極限状態を表します。

　　腐りきった金権政治を正せ。

　　親はその子を信じ切っていた。



§　例文　§

１．私は彼女への思いを断ち切ることができない。

２．やった！三年かかったが、ついに原文で源氏物語を読み切ったぞ。

３．わかり切ったことを言うんじゃない。

４．澄み切った青空、なんとさわやかな秋なんだろう。

５．ちょっと彼は自分勝手すぎて、僕はとても付き合いきれませんね。



★　例題　★

1）　男（っぽく／らしく）、思い（抜いて／切って）彼女に思いを（打ち明けたら／打ち明ければ）どうかしら。当たって砕けろよ。

2）　何があったの（　）、彼は（やつれる→　　　　　）切った顔（　）していた。



(^^)前課の解答(^^)

1)　で（原因・理由）／が（自V）／すれすれ／まで（→文型403）

2)　に／に（～に達する）／駆け（→文型094）



## 068 ～際／～間際



名詞：　の　　　　　＋ 際に

動詞：［ます］形 　　　　　 際の ＋ 名詞

名詞：　×　　　　　＋ 間際に

動詞：原形　　　　　　　　 間際だ

　　　　　　　　　　　　　 間際の ＋ 名詞



♪　会話　♪

良子：夕べのあなたの寝る間際の一言が気になって、なかなか寝つけなかったのよ。

李　：ごめん、ごめん。提案書を書き終わってなかったもんだから、焦りぎみだったんだ。

良子：間際になって慌てるのは、あなたの悪い癖ね。仕事のとばっちりを受けるのは真っ平御免よ。



♯　解説　♭

　「～際／～間際」は「～する直前に～」を表す点では共通しています。なかでも「～間際」は特に用法上の制約もなく、ひろく直前を表すことができます。

　一方、「～際」は「名詞＋の際」の時は「きわ」と読み、それ以外は「ぎわ」と読みますが、「いまわの際」「往生際」「去り際」など、死や別離と関係する慣用的言い方がほとんどです。

　注意してほしいのは、漢字「際」を使って「～とき」を表す「～際（さい）」（→文型098）と読む用法があることです。接続の違いに注意してください。

　　別れ際（ぎわ）に彼女の手を握った。（動詞［ます］形：～する直前に）

　　別れる際（さい）に彼女の手を握った。（動詞普通形：～するとき）



§　例文　§

１．そのマラソン選手は、ゴール間際で倒れた。

２．出発間際になって、彼は突然「行かない」と言い出した。

３．父は死に際（＝いまわの際）に、息子たちへの遺言を残した。

４．父は死ぬ間際に、母の手を握って「ありがとう」と言った。

５．昔の武士は、散り際を大切にしたと言われる。



★　例題　★

1）　試験（まぎわ／ぎわ／さい）になって慌てることがない（ために／ように）、今から勉強し（てある／ておく）（こと／もの）だね。

2）　帰国間際（　）なって、現金とパスポートが（紛失する→　　　　　　　）こと（　）気がついた。



(^^)前課の解答(^^)

1)　らしく（→文型174／→文型450）／切って／打ち明けたら

2)　か（疑問句の「か」）／やつれ／を（→文型466）



## 069 ～極まる／～極まりない／の極みだ



名詞・名詞句：　×　　＋　　極まる

ナ形容詞　　：　×　　　　　極まりない

　　　　　　　　　　　　　　の極みだ



♪　会話　♪

李　：小学校の同窓会の折りに、６年の時の担任の先生が感極まって泣き出してね。

良子：先生に昔のお礼をちゃんとしたの。カラオケに夢中だったら、失礼極まりないわよ。

李　：そんなことするはずないだろ。先生が僕のことよく覚えてくれていて感激の極みだったよ。



♯　解説　♭

　この三つの表現は形は違っていますが、どれも程度が極度であることを表す点で共通です。漢語名詞やナ形容詞の語幹と結びつくことがほとんどで、いいことにも悪いことにも使われます。同義表現に「名詞＋の至りだ」（→文型355）がありますが、いいことに使われます。しかし、どちらも文章語ですから、特に改まった場での会話でない限り、口語として使われることはほとんどありません。



§　例文　§

１．酒・麻雀・女遊びと、君の生活は不健康極まりない。

２．どうして自殺なんて！そんなに苦しんでいたのなら、なぜ一言、僕に話してくれなかったのかと、残念極まる。

３．テレビはつけっぱなし電気もつけっぱなし、不経済極まる。

４．不眠不休で子供を看護をした母も、とうとう疲労の極みに達した。

５．女性一人で、真夜中に見知らぬ外国の街を出歩くなんて、危険極まりないことだ。



★　例題　★

1）　目上の人（について／に対して）「さん」づけもしないで呼び捨てにする（なんか／なんて）、無礼の（極まる／極みだ）。

2）　老人を食い物（　）する霊感商法の手口は、詐欺そのもの（　）。（卑劣だ→　　　　　　　）極まりない。



(^^)前課の解答(^^)

1)　まぎわ／ように（目的→文型153）／ておく／こと（→文型084）

2)　に／紛失している（一般動詞の現在形は「～ている」）／に



## 070 ＊～くせに／＊～くせして



名詞　　　　：　　　　の 　 　　 ＋　　くせに

動詞・形容詞：普通形＜ナ形ーな＞ 　　 くせして



♪　会話　♪

良子：一日中、ずっと家にいたくせに、部屋が少しも片づいていないじゃないの？大人のくせに、自分の身のまわりの始末もできないのね。

李　：この掃除機、新しいのに力がないよ。

良子：ちょっと、私の話をはぐらかさないでよ。掃除機のせいにするつもり？いいわけもいいとこね。



♯　解説　♭

　「～くせに／～くせして」は逆説「のに」のグループですが、非難・軽蔑・反発の感情を強く表します。「のに」に置き換えることができますが、「のに」は失望・残念・不安などの感情が現れます。また、「くせに」は用法上の制約があって、必ず人が主語で、同一主語文でなければ使えません。→例題1)

　　僕の部屋は風呂もないのに（×くせに）、家賃が六万円もするんです。

　この他、「～にもかかわらず」が「のに」のグループですが、客観的な判断を表しています。つまり、話者の感情の違いによって使い分けられているのです。

　　あいつは金持ち　なのに　　　　＜残念・失望＞　けちだ。

　　　　　　　　　　のくせに　　　＜非難・蔑視＞

　　　　　　　　　　にもかかわらず＜客観的判断＞



§　例文　§

１．弱いくせに、口ばかりが達者な奴だ。

２．事情も知らないくせに、他人のことに口を挟むな。

３．わかってもいないくせして、わかったような口を利くな。

４．マイクを握ったら離そうとしない。下手なくせに好きなんだから困ったもんだ。

５．いつもはオートバイを乗り回しているじゃじゃ馬のくせに、見合いとなると神妙にしている。



★　例題　★

1）　奥さんが必死で働いている（のに／くせに）、彼は家で朝から酒浸りと（なっている／きている）。あれじゃそのうち奥さんに愛想を（つかす／つかされる）よ。

2）　彼は（知る→　　　　　）くせに、私（　）は（知る→　　　　　　）ふりをしていた。



(^^)前課の解答(^^)

1)　に対して（→文型322）／なんて（→文型274）／極まる

2)　に（「～を食い物にする」は慣用語）／で／卑劣



## 071 ＊～くらい／＊～頃



数量　　　：　×　　＋　　ぐらい／ほど／ばかり

名詞　　　：　×　　＋　　ぐらい／ほど

こ・そ・あ：　×　　＋　　くらい

日時・年齢：　×　　＋　　ぐらい／頃



♪　会話　♪

山田：６時頃から２時間ぐらいどうだい、一杯？残業続きだから、たまには気分転換でもしようよ。

李　：いいねえ、隣のビルの屋上ビアガーデンはどう？ところで、何人ぐらい集まりそうなの？

山田：５人ほどだよ。いつもの顔ぶれさ。

李　：せっかくだから、課長も誘ってみたら？



♯　解説　♭

　だいたいの数量を表したいときは「～くらい」を使えば、どんな場合も可能です。読み方は人によって少し異なるのですが、「こ・そ・あ」につくときは「くらい」、それ以外は「ぐらい」と覚えてください。

　「10時頃・三月頃…」のような時を表す数詞につく「～頃」の使い方は初級で習ったと思いますが、「終わり頃・若い頃・その頃…」のように数字を含まない名詞・形容詞について「～のとき／～の時期」を表します。後者は概数ではないので、「ぐらい」が使えません。

　時以外の数量につくときには「ぐらい・ほど・ばかり」のどれも概数表現として使えますが、「10人ぐらい」は9～11人、「10人ほど」は多くても10人（9～10人）、「10人ばかり」はやや多い10～11人といった語感を持っています。



§　例文　§

１．風邪で三日ぐらい（⇔ほど／ばかり）休んだ。

２．それはメロンぐらい（⇔ほど＞の大きさでした。

３．一ヶ月ぐらい（⇔ほど／⇔ばかり）帰国しますが、留守中よろしくお願いします。

４．今日、帰りは八時ぐらい（⇔頃＞になるよ。

５．買ってあげてもいいけど、その自転車の値段はどのくらい（⇔どれほど）するの？



★　例題　★

1）　わずか一年（ぐらい／頃）で、こんなに日本語が上手に話せる（ように／ことに）なる（というのは／とは）驚きましたよ。

2）　さすが元電気技師（　）（　）あって、壊れたテレビをたった30分ぐらい（　）修理（する→　　）終えた。



(^^)前課の解答(^^)

1)　のに／ときている（→文型229）／つかされる（受身）

2)　知っている／に／知らない（→文型378）



## 072 ＊～くらい



名詞　　　　：　　　　× 　 　＋　　くらい（ぐらい）

動詞・形容詞：普通形＜ナ形ーな＞

（注：「こ・そ・あ・ど」接続する時を除けば「ぐらい」が普通）



♪　会話　♪

良子：わざわざ出かけて来たのだから、お茶の一杯ぐらい入れてくれてもいいと思うけど。

小孫：揚げ物の最中だから待ってよ。一口食べれば、僕の料理の腕がどのくらいかわかるよ。

良子：それにしても孫君はまめね。いつも自炊してるの？

小孫：自炊しなけりゃ、僕たち留学生は生活できないよ。



♯　解説　♭

　程度を表す「～くらい」の用法ですが、総じて言えるのは低いレベルの例示に多く使われます。「～ほど」（→文型39２）も同様に程度を表します。

　例えば下の例で「～ほど」を使った場合、「～ぐらい」で表現された「新聞を読むわずかな時間もない」という話者の失望や残念な感情は消え、普通の客観的な程度の例示になります。

　　忙しくて、例えば新聞を読む時間がないぐらいだ（・ほどだ）。

　そして、例文３～５や下例のように、「そんな簡単でささやかなこと」という最低限の程度を例示する文では「ほど」が使えなくなります。→例題1)

　　ひらがなぐらい（×ほど）読めますよ。馬鹿にしないでください。

　　遅れるときは電話ぐらい（×ほど）しなさい。



§　例文　§

１．この一ヶ月というもの、忙しくて新聞を読む暇もないぐらい（⇔ほど）だ。

２． 彼女の清潔癖は、ほとんど病的なぐらい（⇔ほど）だった。

３．転んでちょっとけがをしたぐらいで、大げさに騒ぐな。

４．手紙の一本ぐらいくれてもいいのに、日本に行ってから何の音沙汰もない。

５．食事の前には、手ぐらい洗いなさい。



★　例題　★

1）　馬鹿（に／を）しないでください。これ（くらい／ほど）のことは、子供に（だって／って）できますよ。

2）　その事件が（起こる→　　　　）のは、それは（不気味だ→　　　　　）ぐらい（静かだ→　　　　　）ある夜のことだった。



(^^)前課の解答(^^)

1)　ぐらい／ように（→文型446）／とは（→文型242）

2)　だけ（～だけあって→文型132）／で／し（→文型429）



## 073 ＊～ぐらい～はない



名詞　　　　：　　　　× 　 　 　＋　ぐらい　～　はない

動詞・形容詞：普通形＜ナ形ーな＞

（注：「こ・そ・あ・ど」接続する時を除けば「ぐらい」が普通）



♪　会話　♪

佐藤：君と会ってるときは楽しいけど、別れるときぐらい辛いことはないよ。

真理：毎日会えるのは嬉しいけど、会社の方も頑張ってね。

佐藤：ありがとう。でも、会わなきゃ夜が長すぎるよ。ひとりだったら、もうとっくに崩れてるな。

真理：私だって後ろ髪を引かれる思いなのよ。



♯　解説　♭

　「～ぐらい～はない」は「他と比べても、それ以上のものはない」という最高の程度を表します。この用例は「～ほど～はない」（→文型395）文型を使って表せます。

　　自分の家ぐらい（・ほど）いいところはない。

　　あの人ぐらい（・ほど）自分勝手な人はいない。

　しかし、蔑視や嫌悪の感情を含む時は「ぐらい～はない」の方が多く使われます。つまり、驚きや怒りや蔑視などの話者の感情が強く表れるのは「ぐらい～はない」で、「～ほど～はない」は客観的な説明になります。



§　例文　§

１．言葉もわからない外国で、病気をするぐらい不安なことはありません。

２．何もすることがないぐらい、辛いことはない。

３．陰口ぐらい聞いていて嫌なものはない。

４．お前ぐらい馬鹿な奴は見たことがない。

５．見せかけの親切ぐらい、人を傷つけるものはない。



★　例題　★

1）　あの時ぐらい（恥ずかしく／恥ずかしい）思いをしたこと（は／が）なかった。穴があったら入りたいぐらい（だ／だった）よ。

2）　あいつ（　）（　）（　）むかつく奴（　）いない。顔を見る（　）さえ（嫌だ→　　　　　）ぐらいだ。



(^^)前課の解答(^^)

1)　に／くらい／だって（「～でも」の口語形→文型198）

2)　起こった／不気味な（ナ形）／静かな（ナ形）



## 074 ～ぐらいなら、（むしろ）～



名詞　　　　：　　× 　 　　　＋　 ぐらいなら 、(むしろ)～

動詞・形容詞：普通形＜ナ形ーな>

（注：「こ・そ・あ・ど」接続する時を除けば「ぐらい」が普通）



♪　会話　♪

李　：あれっ、また計算が合わないや。

山田：帰って休んだ方がいいよ。疲れがたまってるんだろ。

李　：女房からなんだかんだと小言を言われるぐらいなら、会社にいた方がずっと気楽なんだよ。

山田：そんな思いをするぐらいなら、いっそ結婚しなければよかったのに。



♯　解説　♭

　「Ａぐらいなら、（むしろ）Ｂ」文型は、多くは文末で「～方がいい／方がましだ／～なさい」などと呼応します。そして例文１～４のように、最低の事態Ａを条件にして、そのＡを強く否定し、対立するＢの選択を打ち出す表現です。上の例文は全て「～より、むしろ～」を使って表すことができますが、相手に対する詰問や非難の感情を込めるときは「Ａぐらいなら、（むしろ）Ｂ」の方が釣り合います。→例題1)

　　負けて泣く　ぐらいなら、　　勝つために泣け。

　　　　　　　　より、むしろ

　しかし、例文５のようにＡを否定しないで「どちらかと言えばＢの方が適切だ」という選択のときは「～ぐらいなら、（むしろ）～」が使えません。



§　例文　§

１．あんな男と結婚するぐらいなら（⇔より）、死んだ方がましだわ。

２．途中で投げ出すぐらいなら（⇔より）、むしろ初めからやらない方がいい。

３．負けて泣くぐらいなら（⇔より）、勝つために泣け。

４．君に金を貸すぐらいなら（⇔より）、どぶに捨てた方がましだ。

５．あの人は学者と言うより（×ぐらいなら）、むしろ評論家と言った方がいいだろう



★　例題　★

1）　今頃になって後悔する（より／ぐらいなら）、どうして（あの／この）時、私の忠告を（聞く／聞こう）としなかったのか。

2）　最近（　）は、この種の電気製品は修理（　）出す（　）（　）も、むしろ新品を買った方（　）安くつくんだ。



(^^)前課の解答(^^)

1)　恥ずかしい（→文型022）／は／だった（あの時＝過去）

2)　ぐらい／は／の（名詞句を作る「の」）／嫌な（ナ形）



## 075 ～ぐるみ



名詞　：　×　　＋　ぐるみ



♪　会話　♪

李　：バス旅行中の日本人たちが強盗に身ぐるみ剥がれたけれど、命には別状なかったらしいね。

山田：話しがうまくできすぎてて、あれでは運転手ぐるみの犯行だと疑われても言い開きができないね。

李　：その点、日本は安全でいいね。安全がただの国は珍しいよ。



♯　解説　♭

　接尾語「ぐるみ」は「～を含めて全部・全員」を意味します。そして、「～ぐるみで～する」「～ぐるみの＜名詞＞」形がよく使われます。

　　家族ぐるみで旅行する　　→　　家族ぐるみの旅行

　接尾語「毎（ごと）」（→文型088）にも「そのまま全部」を意味する用法がありますが、「毎（ごと）」は名詞を分けられない一単位で一体の物としてとらえています。その違いが下の例です。→例題1)2)

　　家族ぐるみで旅行する。　（父も母も兄も姉も、そして私も家族全員で）

　　家族ごと旅行する。（Ａさんの家族、Ｂさんの家族、Ｃ・・・が別々に）



§　例文　§

１．この夏は家族ぐるみでハワイに行きました。

２．この邸宅は土地ぐるみで二億円だそうだ。

３．街ぐるみのゴミを少なくする運動が効を奏して、一年でゴミの量が半減した。

４．身ぐるみ脱いで置いていけ。そうすれば命だけは助けてやる。

５．会社ぐるみで事故の真相を隠蔽していた。



★　例題　★

1）　村（ぐるみ／ごと）の選挙違反が（発覚したが／発覚しても）、当事者たちはそれほど悪いことをしたとは（思っている／思っていない）ようだ。

2）　宿泊料・交通費は言う（　）（　）もなく、サービス料（　）ぐるみで一泊二日２万円のお（得だ→　　　）パック旅行です。



(^^)前課の解答(^^)

1)　ぐらいなら／あの（既知・共通情報は「あ」）／聞こう（→441Ｐ）

2)　で（範囲限定）／に／より／が（「～より～方が～」比較文）



## 076 ＊～げ



形容詞語幹：ー［い］／ー［な］　　 ＋　 げだ

ある　　　：［ます］形　　　　　 　　　 げな　＋　名詞

　　　　　　　　　　　　　　　　　　　　げに　＋　動詞

　　　　　　　　



♪　会話　♪

良子：この店はいつも楽しげな家族連れで一杯ね。ところで今日は何を食べさせてくれるの？

李　：ねえ、外にいるあの子、食堂のサンプルを覗き込んでるけど、とても食べたげだよ。

良子：どうしたのかしら。本当にひもじそうだわ。ホームレスなのかしら。



♯　解説　♭

　「～げ」は外から見ての推量を表す接尾語で、「すこし～そうな様子だ」という意味を表します。希に「大人げがない」のように名詞や、「意味ありげな態度」のように動詞につくこともあるのですが、ほとんどは形容詞の語幹について、ナ形容詞をつくります。この「～げ」は様態の「そうだ」と置き換えが可能です。→例題1)2)

　悲しそうだ・悲しそうな顔　　→　悲しげだ・悲しげな顔

　不安そうだ・不安そうな様子　→　不安げだ・不安げな様子



§　例文　§

１．お前って、本当にかわいげのない女だな。

２．怪しげな男が家の回りをうろついている。

３．彼は何やら言いたげな様子だったが、結局口を開かなかった。

４．あなたを尋ねて男の人が来ましたが、何かいわくありげでしたよ。

５．手塩にかけて育てた娘が嫁ぐ日、父親はどこか寂しげだった。



★　例題　★

1)　男はなにやら意味（ある／あり）げ（の／な）笑いを（浮かべて／浮かんで）、僕を見ていた。

2)　彼は「大丈夫だ。俺（　）任せろ」と言ったが、みんなは（心配だ→　　　　）げ（　）顔を見合わせた。



(^^)前課の解答(^^)

1)　ぐるみ／発覚したが（「が」と「ても」の違い）／思っていない

2)　まで（までもない→文型338）／×／得な（ナ形）



## 077 ＊～こそ



名詞（＋格助詞）　：　×　　＋　　こそ～

これ・それ・あれ ：　× 　　　　 こそ～が、～

（動詞・形容詞には、「て形」「ます形」「～ば」などと多様に接続）



♪　会話　♪

課長：新製品の立ち上がりが今ひとつなので、販促（販売促進）キャンペーンを大々的に打つ。君の出番だよ。

李　：前回は思わしくありませんでしたが、今回こそ成果をあげて、皆をあっと言わせますよ。

課長：それでこそわが社のホープだ。最少の費用で最大の効果をあげてほしいからこその君の起用だよ。



♯　解説　♭

　「～こそ」は前の語を「正に～だ」と強調する副助詞です。「～こそ」については「名詞・これ・それ・あれ」と接続する形や、例文２、３のように「～こそ～が、～」の形も一番よく使われます。→例題1)

　それ以外のものは、「～からこそ／～ばこそ」（→文型050）、「～てこそ」（→文型192）、「～こそあれ／～こそすれ」（→文型078）のように文型を作りますから、別に覚えればいいでしょう。

　なお、限定の「～だけ」との混同がよく起こりますが、「君こそ間違っている」と「君だけ間違っている」は意味が異なりますし、「反対しているのは君だけだ」を「反対しているのは君こそだ」とは言えません。



§　例文　§

１．「どうぞよろしくお願いします。」「いいえ、こちらこそ」

２．彼は学校の成績こそ悪いが、素直でいい子ですよ。

３．口にこそ出しませんでしたが、専務のやり方には賛成ではありません。

４．これこそ私が探し求めていたものです。

５．好きこそものの上手なれ。＜ことわざ＞



★　例題　★

1)　彼は口（だけ／こそ）悪い（が／のに）、根はいたって優しい男なんだよ。むしろ甘言を弄する人間に（だけ／こそ）気をつける（はず／べき）だろう。

2)　今年こそ今年こそと（思う→　　　）ながら、どうも僕って男は結婚運（　）恵まれない（　）か、相も変わらぬ独身暮らしだ。



(^^)前課の解答(^^)

1)　あり／な／浮かべて（他Ｖ）

2)　に（～を～に任せる）／心配／に



## 078 ～こそあれ／～こそすれ



動詞：［ます］形　　＋　　こそすれ

名詞：　×　　　 　＋　　こそあれ



♪　会話　♪

課長：残念だが、昨年始めた新規事業から、年度末をもって撤退することになった。

山田：期待こそあれ、挫折は想像すらしなかっただけに意外です。時、我に利あらずでしたね。

李　：誰もが成り行きを心配しこそすれ、無関心な社員は一人もいませんでしたのに。残念がるでしょうねえ。



♯　解説　♭

　「～こそあれ／～こそすれ」は「～けれども／～ても」を強調する逆説の言い方です。改まった場面では年配者が使うことがありますが、今日では古い書面語ですから、読んでわかれば十分です。



§　例文　§

１．仕事には分業こそあれ、上下、貴賎の区別はない。

２．程度の差こそあれ、誰でも出世欲というものは持っている。

３．あなたには感謝こそすれ、恨みを抱くなんてあろうはずがありません。

４．苦労こそあれ、やはり子育ては楽しいものです。

５．盗みこそすれ、非道はせず。



★　例題　★

1)　彼女は国民的歌手（にとって／として／に対して）、日本人なら知ら（ぬ／ず）人はいないが、名誉、財産（こそあれ／こそすれ）、幸せ少ない女性だった。

2)　お恥ず かしいことながら、英語は（読める→　　　）こそ（　）（　）、話す方　（　）なると、さっぱり駄目なんです。



(^^)前課の解答(^^)

1)　こそ／が／こそ／べき（～はずだ→文型367／～べきだ→文型382）

2)　思い（→文型270）／に（～が～に恵まれる）／の



## 079 ＊～ことか／＊～ことだろう



どんなに ＋　動詞・形容詞：普通形＜ナ形ーな＞ 　＋　ことか

どれほど　　　　　　　　　　　　　　　　　　　　 　 ことだろう

なんど

なんと



♪　会話　♪

李　：忙しくて、てんやわんやなのに、あろうことか、うちのかみさん、風邪を引いちまってね。

山田：なんだ、そんなことか。僕はてっきり奥さんが大病で倒れたのかと、本気で心配してたんだぞ。

李　：「なんだ、そんなことか」はないだろう？女房が寝込むとどんなに大変なことかを思い知らされたよ。



♯　解説　♭

　「～ことか／～ことだろう」は話し手個人の気持ちを表す感嘆表現で、「どんなに／どれほど／何度／なんと」などの副詞と呼応することが多いのでしょう。文末では「～ことか」「～ことだろう」のどちらを使ってもかまいませんが、会話では「～ことだろう／～ことでしょう」や、「なんと～こと！」のように「だろう」も省略して使うことが多いでしょう。「～ことか」はどちらかといえば、書面語に属します。

　感嘆表現には「～ものだ」（→文型421）もありますが、使う場面が異なりますから、併せて参照してください。



§　例文　§

１．君のことをどんなに心配したことか。でも、無事でよかった。

２．何度君に忠告したことか。しかし君はそれに耳を貸そうともしなかった。

３．あれからもう十年か、何と月日の経つのは早いことだろう。

４．いじめを受けて自殺した少年は、どんなに辛く、くやしかったことだろう。

５．あなたのいない毎日が、どれほど寂しかったことか。



★　例題　★

1)　今までに何度死にたいと思った（の／こと）か。（そんな／あんな）時、いつもこの子が私に生きる勇気を与え（てもらった／てくれた）んです。

2)　君のお父さん（　）生きていたら、君の立派に成人した姿を見て、どれ（　）（　）喜んだこと（　）（　）（　）。



(^^)前課の解答(^^)

1)　として（→文型237）／ぬ（→文型121）／こそあれ

2)　読め／すれ／と（～となると→文型253）



## 080 ＊～ことがある／＊～こともある



動詞：た形　　　　　　＋　　ことがある

　　　　　　　　　　　　　　こともある

動詞：原形・ない形　　＋　　ことがある

　　　　　　　　　　　　　　こともある



♪　会話　♪

李　：ちょっと息子のことで残念なことがあってね。

山田：残念って、何が？

李　：息子のサッカー・チームは今まで一度も全国大会まで行ったことはなく、今度こそと応援していたんだが、今一歩のところで負けちゃってね。

山田：うまく行くこともあれば、行かないこともあるさ。



♯　解説　♭

　「～ことがある」「～こともある」は前に来る動詞が原形か過去・完了形かで意味が変わてくるので、注意する必要があります。

　動詞の過去・完了形（た形／なかった形）と結びついたときは過去の経験を表します。しかし、動詞の原形・ない形と結びつくときは「現在もときどき～している」経験や事実を表します。

　　彼には会ったことがある。＜以前＞

　　彼には会うことがある。　＜ 今も、ときどき＞



§　例文　§

１．どこかで見たことがある顔だなあ、えっと、誰だったっけ？

２．○○って何？見たことも聞いたこともないなあ。

３．「猿も木から落ちる」とでも言いましょうか、彼ほどのベテランでも失敗することはあります。

４．言葉遣いを間違うと、相手に誤解されることもあるから、気をつけた方がいい。

５．この子の将来を考えると、心配で夜も眠れないことがある。



★　例題　★

1)　彼（と／に）は知人の葬式で一度顔を（合わせる／合わせた）きりで、ゆっくり（話す／話した）ことはない。

2)　その店には今でも時々（行く→　　　）ことがあるが、彼にはまだ（会う→　　）ことが（ある→　　　）。



(^^)前課の解答(^^)

1)　ことか／そんな（相手の発言を指す「そ」）／てくれた

2)　が（従属節中の主語は「が｝）／ほど／だろう



## 081 ＊～ことができる



動詞：原形　　　＋　　ことができる

（注：する→できる／結婚する→結婚できる）



♪　会話　♪

李　：この夏のボーナスは、期待できそうもないなあ。

山田：うん、会社の売り上げも落ちているし、「減給もやむなし」という声すらあがっているようだしね。

李　：会社に残ることができれば、むしろ、幸せだと思うべきかもしれないね。

山田：ああ、サラリーマンは、つくづく哀しい稼業だよ。



♯　解説　♭

　「ことができる」は「能力があってできる／条件があってできる／技能を体得した結果できる」など広く可能を表すことができる文型です。ただし、「～ことができる」や可能形が使われない動詞があるので注意してください。？？雨が降ることができる／？？雨が降れる。

　おかしいですね。つまり「ある・いる・要る・わかる」などの状態動詞や物が主語になる自動詞「光る・壊れる…」などには可能形がないのです。

　今も、ときどき その他、「～する」動詞や「お～する」などの敬語形は、それぞれ次のようになります。→例題2)

　　研究する→研究できる

　　貸す→お貸しする→お貸しできる



§　例文　§

１．自分ができないことを他人に「やれ」と言うべきではない。

２．きれいごとだけでは、生きてゆくことはできない。

３．資金がもう少しありさえすれば、この事業を軌道に乗せることができるのだが・・・。

４．「小さな火花も広野を焼き尽くすことができる」（中国格言）

５．「愚公山を移す」という寓話の主旨は、「雨垂れ石を穿つ」という格言で表すことができる。



★　例題　★

1)　結婚後も男女別姓に（する／している）ことができるようにする民法改正案（をめぐって／を通して）、国会内外で喧々囂々の大論争が（起こった／起こした）。

2)　プライベート（　）こと（　）ので、私からお（話す→　　　　）できることはこれだけです。



(^^)前課の解答(^^)

1)　と（～と顔を合わせる）／合わせた／話した

2)　行く／会った／ない



## 082 ＊～ことから／＊～ところから



動詞・形容詞：普通形＜ナ形ーな＞ 　＋　 ことから

　　　　　　　　　　　　　　　　　　　　ことからも

　　　　　　　　　　　　　　　　　　　　ところから



♪　会話　♪

李　：日本人は、人前で恥をかきたくないと思うことから、外国語を話す力が身につかないんじゃないのかなあ？

良子：耳の痛い話だけど、的を射ていると思うわ。日本文化のことを「恥の文化」と言った人もいたわ。

李　：言い得て妙だなあ。そんなところから「自己主張が苦手な日本人」と言われるのかもね。



♯　解説　♭

　これらは根拠や理由を述べる「から」から生まれた表現です。例えば例文１、２は判断の根拠や理由を表していて、文末では「～と考える／～とわかる」や「～らしい／～ようだ」がよく現れまます。この場合は「～ことから」も「～ところから」も使えます。

　例文３、４は「百科事典・東洋のベニス…」と呼ばれるようになった由来を説明する文で、「～ところから」は使えません。これは「～ことから～と言われる／と呼ばれる」と文型として覚えた方がいいでしょう。

　例文５は実例を挙げる用法で、多くは「～ことからも～がわかる／うかがえる／うかがい知ることができる」という形で使われます。この場合も「～ところから」は使えません。それは「～ことから」は「～という事実から」、「～ところから」は「～という状況・場面から（主として視覚判断）」という違いから生じています。→例題1)



§　例文　§

１．足跡が大きいことから、どうやら犯人は男らしい。

２．何でも自分一人でやろうとするところから、無理が生じる。

３．彼は物知りであるところから、生き字引と言われている。

４．彼の絵は独創性にあふれ、色彩感覚も豊かなことから、現代のピカソと呼ばれている。

５．古代人がいかに高い文明をもっていたかは、今まで述べてきたことからもおわかりいただけると思います。



★　例題　★

1)　各地の古代遺跡から大陸製の銅鏡が大量に発掘（した／された）（こと／ところ）からも、紀元前には既に活発な交易が（行って／行われて）いたことがうかがえる。

2)　彼は面倒見がいい（　）（　）から、部下から（　）厚い信頼を（受ける→　　　　　　）。



(^^)前課の解答(^^)

1)　する／をめぐって（→文型470／→文型478）／起こった（自Ｖ）

2)　な（カタカナ形容詞はナ形）／な／話し（敬語形→文型019）



## 083 ～如し／～如く／～如き



名詞・副詞：の ／が　　＋　　 如し

動詞　　　：普通形　　　　　 如き ＋　名詞

　　　　　　　　　　　　　　 如く ＋　動詞・形容詞



♪　会話　♪

李　：今度の日曜、結婚記念日だよね。もう十年か、「光陰、矢の如し」とはよく言ったものだ。

良子：色々なことがあったけれど、楽しいことばかり思い出すわ。小平が生まれて生き甲斐もできたし。

李　：僕は何から何までないないずくしだった、あの二人だけの新婚の頃を今更の如く思い出すなあ。



♯　解説　♭

　「～如し」は現代語の「～ようだ」に相当する古語ですが、用法的には慣用的なものに限られています。接続も例文４のように動詞に「が」をつけて用いられることもあります。会話や作文では「ようだ」を使えば十分でしょう。

　速きこと風の如し（如し・ようだ）

　風の如く速し　　（如く・ように）

　風の如き速さ　　（如き・ような）

　なお、例文２のように人称を表す語と接続するときは、「あいつら如き／田中如き」のように「～如き（者）が／如き（者）に」のように「者／人間」が省略されることもあります。→例題1)



§　例文　§

１．その男は鬼の如き形相で、私をにらみつけた。

２．あいつら如き駆け出しの若造に負けてなるものか。

３．その娘は蝶の如く軽やかに、花の如くあでやかに舞った。

４．彼は眠るが如くやすらかに、最期の時を迎えた。

５．今まで述べてきた如く、今回のことにつきましては、当社は無関係でございます。



★　例題　★

1)　彼はお前（如き／如く）が（勝つ／勝てる）相手ではない。今彼と闘うのは、むざむざ（死ぬ／死に）に行くようなものだ。

2)　今回の作戦の失敗は起こるべくして起こったと（言う→　　　　）。当初から指摘されていた（如し→　　　）、この作戦にはそもそも無理が（ある→　　　　）のだ。



(^^)前課の解答(^^)

1)　された（受身）／こと／行われて（他動詞の受身文）

2)　こと／の／受けている（一般動詞の「ている」形は現在形）



## 084 ＊～ことだ



名詞　　　　：　　　の 　 　　＋　　 ことだ

動詞・形容詞：普通形＜ナ形ーな＞



♪　会話　♪

李　：外国語は難しく考えずに、できるところから始めることだよ。習うより慣れろだからね。

百恵：でも私って、いつも中途半端になってしまうの。意志が弱いのかしら？

佐藤：途中で挫折しないためには、欲をかき過ぎないことだね。継続は力なりって言うだろ。



♯　解説　♭

　「～ことだ」は一つ一つの個別事例を取り上げ、例文１、２のように「まさに～だ」と自分の意見・感想・事実を強調するのが特徴です。

　しかし、動詞の原形・「ない」形につくときは、例文３～５のように「（～する／しない）ことが 最善だ」という勧告や忠告の意味を表すことが多いでしょう。実質的には「～方がいい」（→文型388）を断定的に言ったもので、「 ～に越したことはない」（→文型309）とほぼ同義表現になります。

　なお、「～ものだ」（→文型420）は「人間は死ぬものだ 」「成功の裏には苦労があるものだ」のように一般義務や普遍事実を取り上げて強調するので、「～ことだ」と対照的です。→例題1)



§　例文　§

１．やれやれ、一難去ってまた一難とは正にこのことだ。

２．誰でも死は恐いものです。それは当たり前のことです。

３．勝負は最後まであきらめないことだ。

４．捨て身でかかることだ。そうすれば、万に一つのチャンスも生まれる。

５．今更見苦しい真似はしないことだ。言い訳がましい弁解はせず、自分の蒔いた種は自分で刈ることだ。



★　例題　★

1)　疲れた時はね、何も考え（ないで／なくて）ゆっくり休む（ことだ／ものだ）。そうすれば、また元気が湧いてくる（ことだ／ものだ）よ。

2)　すぐに人に（頼る→　　　）ず、先ず自分の力（　）（やる→　　　　）みることだ。



(^^)前課の解答(^^)

1)　如き／勝てる／死に（Ｖ［ます］形＋行く・来る・帰る）

2)　言える／如く／あった（時制に注意）



## 085 ＊～ことだから／～こととて／～こともあって



名詞　　　　：　　　　の　　　　　＋　　ことだから

動詞・形容詞：普通形＜ナ形ーな＞　　　　ことだし

　　　　　　　　　　　　　　　　　　　　こととて

　　　　　　　　　　　　　　　　　　　　こともあって



♪　会話　♪

良子：小平がお隣の柿を盗み食いしたらしいの。お隣さんも子供がやったことだし、大目に見てくれたけど、恥ずかしいと言ったらありゃしないわ。

李　：僕も子供の頃に似たような経験をしていることもあって、注意しにくいなあ。

良子：蛙の子は蛙っていうわけね。



♯　解説　♭

　どれも原因・理由の表現で、「他でもない～＜ひと・こと・もの＞だから」とそれ自身が持っている固有の理由を取り上げることに特徴があります。「なにしろ／なにせ～（ことだ）から」と副詞と一緒に使うといいでしょう。

　「～ことだから」は話し言葉で多く使われ、「～こととて」は手紙や書き言葉で多く使われると言う違いはありますが、例文1～4のように同じように使えます。なお、「～こともあって」は「～て」系の理由表現（→資料､）なので、文末で意志・推量表現が使えないという制約があります。

　注意しなければならないのは、「～こととて」には例文５のように「～ことであっても」と逆説条件の用法があることで、この場合、「～ことだから／～ことだし／～こともあって」は使えません。



§　例文　§

１．慣れぬこととて時間ばかりがかかり、少しもはかどらない。

２．何しろ一刻を争う時のことだったから、上司の判断を待っている余裕はなかったんです。

３．病弱なこともあって、少年は読書を友として育った。

４．天候も不順なことですし、くれぐれもお体にお気をつけください。

５．いくら子供がやったこととて（×ことだから）、謝って済まないこともある。



★　例題　★

1)　社長不在の（ことだし／こととて）、この件については日を改めてご返事（して／させて）（いただき／いただけ）ませんか。

2)　遅刻常習犯の彼の（　）（　）だから、今日も（遅れる→　　　　）来る（　）決まっている。



(^^)前課の解答(^^)

1)　ないで（→文型257）／ことだ／ものだ（→文型420）

2)　頼ら（→文型121）／で／やって（～てみる→文型197）



## 086 ＊～ことなく／～ことなしに／～ことなくして～ない



動詞：原形　　＋　こと（も）なく

　　　　　　　　　ことなしに

　　　　　　　　　ことなくして　～　ない



♪　会話　♪

山田：よく「万里の長城を見ることなくして、中国を見たと言うなかれ」って言われるね。

李　：そんなことで、中国を見たことにはならないよ。

山田：どういう意味？

李　：広大な内陸部の農村地帯を見ることなしに、中国も中国の抱える悩みも見えないってことさ。



♯　解説　♭

　「～ことなく」は「～しないで～する」、「～ことなしに」は「～しない状態で～する」という意味を表します。置き換えが可能な場合が多いのですが、「～ことなく」は「～ことなしに」より広範に使えます。

　　箸を使うことなく（？ことなしに）、スプーンで食べた。

　　ご飯を食べることなく（・ことなしに）、学校へ行った。

　「～ことなくして～ない」は常に文末で否定形（「ない」形）や否定を意味する語と呼応し、「～しなければ、～決して～ない」という意味を表します。例えば、例題1)も「～ことなくして」を使うと、後件は「社会を変えていくことは不可能だ」となります。



§　例文　§

１．彼は雨の日も風の日も、休むことなく働き続けた。

２．相手の心を傷つけることなしに、間違いを正すことは難しいことだ。

３．原則を変えることなく、現実に柔軟に対応することが大切だ。

４．犠牲を払うことなくして勝利を得ることは不可能だ。

５．額に汗して働くことなしに手に入れた泡銭は、身に付かぬものだ。



★　例題　★

1)　暴力（による／に基づく）こと（なしに／ないで／なくしては）、社会を変え（てくる／ていく）ことは可能だ。

2)　心（　）（　）お二人の前途を祝福いたします。いつ（　）（　）も変わること（　）（　）お幸せに。



(^^)前課の解答(^^)

1)　こととて（丁寧）／させて（→文型102）／いただけ（許可）

2)　こと／遅れて／に（～に決まっている→文型305）



## 087 ＊～ことに（は）



感情・感動を表す形容詞：ーい／ーな　　＋　ことに（は）

感情・感動を表す動詞　：た形



♪　会話　♪

李　：大学時代の友達が結婚することになったよ。びっくりしたことに、相手は現役の女優だったんだよ。

山田：それじゃ、スケジュールがびっしりで、会うこともままならないだろうな。

李　：意外なことに、先週仲間で集まったときに、彼女も来てたよ。実を言うと、俺、彼女のファンだったんだ。



♯　解説　♭

　「～ことに（は）」は感情・感動を表す形容詞や、動詞の完了形（「た」形）について、文頭で話者の気持ち・感情を強調する表現です。普通は話者が驚き・喜怒哀楽などの感動をもってとらえたときに使われます。

　この「～ことには」はもう起こった既定事実の表現なので、文末も「～した／～だった／～のです」が多く現れます。「～ことには～した」と覚えればいいでしょう。文末で動作動詞の辞書形（＝未来）や、「～だろう」「～つもりだ」や「～たい」などの推量・意志・希望表現は使えませんから注意してください。



§　例文　§

１．不思議なことに声はするのに姿が見えないのです。

２．悔しいことに、僅か一点差で相手チームに負けてしまった。

３．ありがたいことには、五体満足で健康な体を両親から授かりました。

４．困ったことに、今日は事故で電車が止まって、約束の時間に間に合わなくなった。

５．不幸中の幸いとでも言いましょうか、幸いなことに、軽いけがで済みました。



★　例題　★

1)　（てっきり／きっと）独身かと思っていたら、（驚く／驚いた）（ことは／ことに）彼女は三人の子持ちだった。

2)　（信じられる→　　　　　　）こと（　）、あの空手四段の彼が、お酒が一滴も（飲める→　　　　）そうだ。



(^^)前課の解答(^^)

1)　による（方法→文型346）／なしに／ていく（→文型177）

2)　から／まで／なく



## 088 ＊～毎に／＊～おきに



数詞：　＋　毎に

　　　　　　おきに



♪　会話　♪

李　：彼は今時珍しい親孝行だよ。四日おきに養老院の母親のもとへ通ってるらしいよ。

真理：確か彼は三人兄弟だったわね。交代で毎日誰かが訪ねてるのかしら？

李　：二日おきぐらいになるらしいよ。みんな所帯持ちらしいから、色々事情があるのだろうよ。



♯　解説　♭

　下図は「毎に」と「おきに」の違いを表したものです。例えば「一週間毎に・一ヶ月毎に・一年毎に」は「毎週・毎月・毎年」の意味になりますし、「一週間おきに・一ヶ月おきに・一年おきに」は「隔週・隔月・隔年」の意味になります。

　　毎に　：○●　○●　○●　○●　　二駅毎にトイレがある

　　おきに：○○　●　○○　●　○○　二駅おきにトイレがある

　この例外は時間（秒・分・時間）と距離（ミリ・センチ・メートル・キロ）で連続したものを区切るときで、この場合は違いはありません。その違いを敢えて挙げれば、例えば「１０分毎に」は「１０分の中で一回」ですが、「１０分おきに」は「１０分終了後一回」でしょう。これ以外に「毎」には「魚を骨ごと食べる」（一緒に全部）、「一雨毎に暖かくなる」（変化）、「家毎に新聞を配達する」のような用法があります。



§　例文　§

１．私の団地では、一ヶ月毎に掃除当番がまわってきます。

２．この雑誌は、一ヶ月おきに発売されています。

３．この歩道には五メートル毎に（⇔おきに）木が植えられている。

４．三分おきに（⇔毎に）電車が通ります。

５．一雨毎に暖かくなります。



★　例題　★

1)　毎朝、一軒（ごとに／おきに／たびに）新聞を配達するんですが。季節の移り変わりが肌身に（感じ／感じられ）、（それで／それでは）結構気に入っているんです。

2)　医者の話によると、腰痛（　）は水泳が一番だとの（　）（　）なので、二日おきに市営プールに（行く→　　　　）は、体を鍛えています。



(^^)前課の解答(^^)

1)　てっきり（事実は逆が「てっきり」）／驚いた／ことに

2)　信じられない／に／飲めない



## 089 ＊～ことにする／＊～こととする／＊～ことにしている



動詞：原形／ない形　　　＋　　ことにする

（受身形・可能形は不可）　　　　こととする

　　　　　　　　　　　　　　　ことにしている



♪　会話　♪

李　：この春、中国に里帰りすることにしているんだけれど、今年は何かと物入りで大変だよ。

山田：四月五日に会社の創立記念パーティがあるけど、ぶつからないの？

李　：その日までには帰国するから大丈夫だよ。子供の学校も始まるしね。



♯　解説　♭

　「～ことにする」は自分の意志で決定することを表しますが、他動詞の「～ことに決める」と同義です。「～ことにする」と「～こととする」は基本的には同じ意味を表しますが、「～ことにする」は自らの考えを変えた結果、「～こととする」は相手方の考え方にそのまま同意した結果を表します。そして、「～ことにしている」と「ている」形になったときは、自らの予定・計画或いは自己の習慣を表すようになります。

　　来年、日本に留学することにしています。　　　　＜自分の予定＞

　　毎朝、健康のために早起きすることにしています。＜自分の習慣＞

　注意してほしいのは「～ことにする」と「～ことになる」（→文型090）との違いですが、これについては次項を参照してください。



§　例文　§

１．卒業したら帰国することにしていたが、もう一、二年ほど日本に残ることにした。

２．この議論は、このまま続けてもらちがあかない。一旦、　　棚上げすることにしないか。

３．君には失望した。今後一切君には頼らないことにする。

４．結婚以来、給料はそっくり妻に渡すことにしている。

５．私は大切な用件は電話でなく、必ず会って直接伝えることにしている。



★　例題　★

1)　彼に頼ん（でみる／でいる）こと（にする／になる）が、彼の賛同が（得る／得られる）かどうかはわからないよ。

2)　彼（　）口が軽いから、このことは彼には（話す→　　　　　）ことに（する→　　　　）か。



(^^)前課の解答(^^)

1)　毎に／感じ（形は受身だが、自然・自発表現）／それで（理由）

2)　に（→文型336）／こと（伝聞→文型209）／行って（→文型188）



## 090 ＊～ことになる／＊～こととなる／＊～ことになっている



動詞：原形／ない形　　　＋　　ことになる

　　　　　　　　　　　　　　　こととなる

　　　　　　　　　　　　　　　ことになっている

　　　　　　　　　　　　　　　こととなっている



♪　会話　♪

李　：僕は日本が好きだから言うんだけれど、過去の過ちを認めないということは、未来に過ちを再び犯すこととなるんじゃないのかなあ。

山田：最近の歴史教育論争のことを言ってるんだね。

李　：うん、昨夜、その討論番組をテレビで見てね。

山田：でも、どのみち事実が勝つことになると思うよ。



♯　解説　♭

　「～ことになる」は「必然的に～なる」か、国や会社・学校などの決定を表しますが、自動詞の「～ことに決まる」と同義です。「～ことになる」は以前の状態や決定が変わった結果を、「～こととなる」は「自然ななりゆき」を表すことが多いでしょう。そして、「～ことになっている／～こととなっている」は会社や学校などで決まった予定や、法律・規則・風俗・慣習を表すようになります。

　　日本では葬式には黒い服を着ることになっている。　　＜風俗・慣習＞

　　会議中、タバコを吸ってはいけないことになっている。＜規則＞

　　来年、出張で中国に行くことになっている。　　　　　＜予定＞

　「～ことにする」（→文型089）と「～ことになる」の違いは、自己の意志が関わる決定は「～ことにする」、会社・組織などの周囲の決定は「～ことになる」、自己の習慣は「～ことにしている」、社会や周囲が決めた規則や風俗や慣習は「～ことになっている」となることです。



§　例文　§

１．私たち、この度、結婚することになりました。

２．ここで君がこの任務を投げ出したら、今までの君の努力は、全て「水泡に帰す」ことになるよ。

３．この会場で、来月外国人スピーチコンテストが開かれることになっています。

４．お買いあげいただいて一週間以上たった品は、返品できないこととなっております。

５．日本では車は左側を通行することになっている。



★　例題　★

1)　守れない約束は、最初からしない（べきだ／ことだ）。そう（する／しない）と、信用を失う（ことに／ように）なるよ。

2)　幹部会の決定（　）、この件は山田君（　）やらせて（みる→　　　）じゃないかということになった。



(^^)前課の解答(^^)

1)　でみる（→文型197）／にする／得られる（可能形）

2)　は（「～は～が～」文）／話さない／しない（＝～ませんか）



## 091 ことによると～／ことによれば～／ことによったら～



ことによると　　名詞　　　　：　　　× 　 　　～ かもしれない

ことによれば　　動詞・形容詞：普通形＜ナ形ー×＞

ことによったら



♪　会話　♪

李　：中座したのでわからないけど、ことによると彼に迷惑をかけてしまったのかもしれないな。

山田：君には世話になるばかりだと恐縮していたから、君の役に立てたと喜んでいるんじゃないかな。

李　：大した世話なんかしてないよ。彼一流の社交辞令さ。ことによれば勝手な奴だと笑ってるかもしれないよ。



♯　解説　♭

　「ことによると／ことによれば／ことによったら～かもしれない」は「もしかして／もしかしたら／ひょっとして／ひょっとしたら～かもしれない」と基本的には同じ意味で、どれもすべて「～の可能性は少ないだろうが～かもしれない」という気持ちを表しています。また、明示されなくても「たぶんそうならないはずだが」という予想が前提になっているので、「そんなことはないと思うが～かもしれない」のように作文するといいでしょう。

　（そんなことはないと思うが）ことによると、その噂は事実かもしれない。



§　例文　§

１．予定では10日ですが、ことによったら、一日ぐらい遅れるかもしれません。

２．会議には出席するつもりでおりますが、ことによれば多少遅れるかもしれません。

３．彼女は見た目は若いけれど、ことによれば四十歳を過ぎている可能性がありますね。

４．ことによると、関東大震災は本当に起こるかもしれない。

５．ことによるとＡ国の民族紛争は内乱に発展する恐れがある。



★　例題　★

1)　天気予報（に／で）は、雨の（恐れ／嫌い）はないと言っているが、ことによったら外れる（だろう／かもしれない）。

2)　ことによれば、近いうち（　）二人は離婚ってことに（なる→　　　）（兼ねる→　　　　　）ね。



(^^)前課の解答(^^)

1)　ことだ（→文型084）／ない（→文型203）／ことに

2)　で（根拠）／に（使役文：「～が～をやる」）／みよう（→文型440）



## 092 ～ことは～が、～／～には～が、～



名詞　　　　：である 　 　　＋　ことは　～　が、～

動詞・形容詞：普通形＜ナ形ーな＞

　

名詞　　　　：である 　 　　＋　には　　～　が、～

動詞・形容詞：普通形＜ナ形ー×＞ 　



♪　会話　♪

山田：心配な点もあるにはあるが、いつまでも心配してるだけでは先へ進めないよ。

李　：君はいつも前向きだなあ。君の爪の垢でも煎じて飲んだ方がよさそうだよ。

山田：僕は前向きなことは前向きなんだけど、夢中になるとほかが見えなくなっちゃってねえ。



♯　解説　♭

　「ＡことはＡ」は同語を繰り返して、「Ａであるのは確かですが、しかし、～」とＡを認めながら、実際はいろいろ矛盾する問題があることを指摘する表現で、「ＡにはＡ」も同じ意味を表します。形に注意してください。

　　美しいことは美しい　→　美しくはある　＜イ形＞

　　元気なことは元気だ　→　元気ではある　＜ナ形＞

　　飲むことは飲む　　　→　飲みはする　　＜動詞＞

　否定形は「美しくないことはない／元気でないことはない／飲まないことはない」「美しくなくはない／元気でなくはない／飲まなくはない」となります。この「～ないことはない」（→文型256）は婉曲な肯定になります。



§　例文　§

１．刺身は食べられるには食べられるが、それほどおいしいとは思わない。

２．その会合に参加することはするが、あまり気が進まない。

３．彼女は美しいことは美しいが、少しそれを鼻にかけている。

４．その件は、私から彼に話すには話してみるが、説得する自信はないねえ。

５．彼のことは好きなことは好きだけど、結婚したいほどじゃないわ。



★　例題　★

1)　事情を（知りたい／知りたく）はあるが、彼が言い（たければ／たくなければ）、敢えて（聞く／聞こう）とは思わない。

2)　難しいこと（　）難しい（　）、かといって、全く歯が立たないほど（難しい→　　　　　）はない。



(^^)前課の解答(^^)

1)　で（理由）／恐れ（→文型020／→文型063）／かもしれない

2)　に（→文型016）／なり／兼ねない（→文型043）



## 093 ＊～ことはない／＊～こともない



動詞：原形　＋　ことはない

　　　　　　　　こともない



♪　会話　♪

李　：君が謝ることはないよ。あくまでも共同作業なんだから、今後の対応策をつめる方が肝心だよ。

山田：自分がやれることはやったんだから、悔いはないと思っていたけど、やはり失敗は骨身にこたえるよ。

李　：今回のことで先方とのお付き合いを深められるなら、「塞翁が馬」でこれ以上のことはないよ。



♯　解説　♭

　「～ことはない／～こともない」は動詞の原形とむすびついたとき、例文１～３のように、「～することはない」は「～する必要はない」＜不必要＞を表します。そして、「～までもない／～には及ばない」（→文型338）と同義表現になります。動詞の完了形（「た」形）と結びついたときは「～したことがある／～したことはない」（→文型080）のように、過去の経験を表します。

　　行くことはない。　＜必要がない＞

　　行ったことはない。＜過去の経験がない＞

　また例文４、５のように、「～ような事態は決して～ない」＜全面否定＞を表すときがありますが、この場合、例題のように「～ことはあっても～ことはない」は対比させて強調する文型もよく使われます。→例題1)



§　例文　§

１．息子はもう中学生なんだし、少々帰りが遅いぐらいで、いちいち心配することはない。

２．焦ることはない。時間はまだ十分にある。

３．誰にもまちがうことはあるんだし、そんなに怒ることもない。

４．体が健康で手に職があれば、どこに行っても生活に困ることはないさ。

５．人の世は、流れ続ける大河のように絶えず変化していて、一刻もとどまることがない。



★　例題　★

1)　彼は正直者で、人に（騙す／騙される）ことはあっ（た　ら／ても）、人を（騙す／騙される）ようなことはない。

2)　君が手伝ってやる（　）（　）はない。親切も度を過ごす（　）、相手のためには（なる→　　　　　）ものだ。



(^^)前課の解答(^^)

1)　知りたく／たくなければ／聞こう（「～（よ）うと思う」の否定形）

2)　は／が／難しく



## 094 ～込む



動詞：［ます］形　　＋　込む



♪　会話　♪

李　：工場の担当者が「品質を工程に作り込む」とか言ってたけど、どういうことか説明してよ？

佐藤：一言では説明できないねえ。品質管理の基礎知識が必要だから、勉強会でも開こうか？

李　： 品質管理は難しいと思い込んでる人が多いよ。専門用語が、いきなり飛び出してくるんだから。



♯　解説　♭

　「～込む」は多くの複合動詞を作ります。意味は場所や状況に入るという原義に近い内部移動と、「十分に～する」から「完全に～する」までの広がりを持った程度深化に分かれます。例えば「地面に杭を打ち込む」は「打って入れる」内部移動ですが、「仕事に打ち込む」は「～に熱中する・～専念する」の意味の程度深化の表現になります。なお「～を投げる→～を投げ込む／～と思う→～と思い込む／～が寝る→～が寝込む」のように、助詞は原則として前の動詞によって決まります。

　内部移動：上がり込む・打ち込む・押し込む・買い込む・詰め込む・連れ込む…

　程度深化：教え込む・考え込む・決め込む・冷え込む・眠り込む・話し込む…



§　例文　§

１．酒と博打にのめり込んだ彼は、借金を抱え込み、やがて貧困のどん底に落ち込んだ。

２．人の弱みにつけ込むやり口は、決して許されることではない。

３．辣腕でならした彼も、退職後めっきり老け込んでしまった。

４．会社の金の使い込みがばれて、彼は首になった。

５．親の遺産を当て込んでいた彼は、自分が相続人から外されていると知らされ、すっかりしょげ込んだ。



★　例題　★

1)　少し冷え（込んで／切って）（きた／いった）ね。寒ければ、暖房を（点こう／点けよう）か。

2)　パソコン市場（　）は、激しい新製品の（売る→　　　）込み合戦が（展開する→　　　　　　）ている。



(^^)前課の解答(^^)

1)　騙される（他Ｖの受身）／ても（条件の逆説）／騙す（他Ｖ）

2)　こと／と（→文型203）／ならない



## 095 これといって～ない／これといった～ない／これという～ない



これといって　　　　　～　　　　ない

これといった　＋　名詞（は／も)　　～　 ない

これという　　＋　名詞（は／も)　　～ ない



♪　会話　♪

佐藤：わが社も創立五周年なのに、これといった記念行事がないのは寂しいな。

李　：入社して日が浅いわけでもないけど、創立記念日だからといって、これといった感慨もないなあ。

山田：僕もさ。ただこの会社は、これといった長所もないかわりに、平々凡々と一生を過ごすにはいい会社だよ。



♯　解説　♭

　これらの文型は常に否定形（「ない」形）と呼応して、「特に＜語るほどのこと・名詞＞はない」という意味を表します。「これといって」はすぐ後ろに動詞や形容詞が続く、「これといった／これという」はすぐ後ろに名詞が続くと覚えておけばいいでしょう。そして用例のほとんどは、「これといってすることもなく／これといった名案も出てこない／これという進展もない」のように助詞「～も」と呼応します。



§　例文　§

１．一日中、これといってすることもなく、平穏ではあるが退屈な日々が過ぎていった。

２．いろいろ相談したが、これといった名案も出て来なかった。

３．これという進展もないまま、和平会談は終わった。

４．別にこれといった理由があるわけではないんですが、どうも不安が残りますね。

５．適当な人材がいればいいのですが、これといった心当たりもありません。



★　例題　★

1)　（これといった／これといって）趣味も、特に（ある／ない）んですが、（特に／強いて）あげれば、晩酌ですかねえ。

2)　この地方（　）は、（　）（　）といって取り上げるほどの特産も（あります→　　　　　　）。



(^^)前課の解答(^^)

1)　込んで（～切る→文型067）／きた（→文型181）／点けよう（他Ｖ）

2)　で（範囲限定）／売り／展開され（受身：「～を展開する」）



## 096 ～ごろ／～盛り



名詞：　×　　　　＋　　ごろ

動詞：［ます］形　　　　 盛り



♪　会話　♪

李　：さあ、食欲の秋だ。柿も食べごろ、さんまも出盛りで安いし、たくさん食べて冬に備えようよじゃないか。

良子：あなたは気楽ね！食べ盛りの子供がいるから、毎週、お米を１０キロも食べるのよ。お金も大変だけど、買い物の帰りがもう大変なのよ。腕は痛くなるし・・・。

李　：運動不足の解消に打ってつけじゃないか。



♯　解説　♭

　「～ごろ」は「10時頃・夕方頃」などの用法の他に、「ちょうど適当な＜とき・もの・状態＞」などの意味を表すことがあります。「～盛り」は「花盛り」のように植物の例もありますが、多くは人間のある段階の絶頂期を表します。

　例えば「食べごろ」は物を食べるのにちょうどいいときですが、「食べ盛り」は中学校の２～３年の一番たくさん食べるピークの年代を表しますし、「年ごろ」は結婚適齢期ですが、「娘盛り」はだいたい16～17歳ごろを指します。

　多くは慣用的に使い方が決まっていますから、自由に造語することはできません。主な接尾語「～ごろ／～盛り」のつく語は例文に入れてありますから、そのまま覚えましょう。



§　例文　§

１．この鞄は手ごろな大きさだし、値ごろだから、これにしよう。

２．娘も年ごろになると、扱いにくくなります。

３．三十代の後半から四十代というのは、男は男盛り、女は女盛りで、人生が一番充実した年代だと言われている。

４．夫はまだ働き盛りなのに、会社からリストラの対象にされています。

５．最近はどこもかしこも、習いごと教室やスポーツセンターが花盛りです。



★　例題　★

1)　うちの子は中三で、育ち（ごろ／盛り）伸び（ごろ／盛り）だが、成績（だけ／ばかり）がなぜか伸びない。

2)　紅葉は今がちょうど（見る→　　　）ごろだよ。今度の日曜日あたり（見る→　　　）（行く→　　　　）か。



(^^)前課の解答(^^)

1)　これと言った／ない／強いて（副詞≒敢えて）

2)　に（「～には～がある」文→文型419）／これ／ありません



## 097 ～さ／～み



形容詞の語幹：＜イ形ー［い］＞　　＋　　さ

　　　　　　　＜ナ形ー［な］＞　　　　　み



♪　会話　♪

百恵：自分で処理できることなら、少しくらい大変でもそうしたら。あの人に借りをつくると、後が面倒よ。

李　：彼のしつこさは人並み外れてるからなあ。いつまでも恩着せがましく言われるのも嫌だし、そうするか。

百恵：高みの見物を決め込むつもりだったけど、こうなったからには、私があなたのために一肌脱ぐわ。



♯　解説　♭

　接尾語「～さ」は多くの形容詞の語幹について、一般属性を表す名詞に変えます。接尾語「～み」は「～ような＜感覚・感情／様子・色・味／ところ＞」などの印象や特徴を表す名詞を作ります。以下が主な「ーみ」のつく形容詞です。イ形：赤み・青み・厚み・甘み・ありがたみ・痛み・うまみ・重み・

　　　面白味・辛み・臭み・苦しみ・強み・弱み・苦み・憎しみ・

　　　深み・丸み・柔らかみ・親しみ…ナ形：憐れみ・真剣味・堅実み・憐れみ…

　「～さ」「～み」の両形がある場合も意味の違いがあり、例えば「深さ」は何メートルか計れますが、「深み」は「深いような感じ／深いと思う場所」ですから、計れません。→例題1)

　　川の深さを測ったら10メートルでした。

　　川の深み（＝深いところ）にはまって溺れた。



§　例文　§

１．可愛さ余って、憎さ百倍。

２．二月も末になると、しだいに暖かさが増してきた。

３．彼女は頭はいいが、人間に暖かみがない。

４．彼は年をとって丸みがでてきたようだね。

５．薬を飲んでしばらくすると、しだいに痛みもやわらいできた。



★　例題　★

1)　記者たちの努力（によって／にとって／について）、某政治家の地位を利用した株取引の真相が（明るさ／明るみ）（を／に）出された。

2)　「いくら勝つためとは言え、僕はそんな汚い手を（使いたい→　　　　）」「それが君の世間を知らない（甘い→　　）だよ。勝つためには手段を（選ぶ→　）ずさ」



(^^)前課の解答(^^)

1)　盛り／盛り／だけ（「～ばかり」は単なる限定ではない→文型362」

2)　見／見（Ｖ［ます］形＋行く）／行かない（提案：～ないか）



## 098 ＊～際（に）／～節（に）



名詞　　　　：の 　 　　　＋　　 際（に／は／には）

動詞・形容詞：普通形＜ナ形ーな＞ 　　　 節（に／は／には）



♪　会話　♪

山田：君と良子さんの出会いのきっかけというのは、一体何だったの？

李　：良子とは大学のサークルで知り合ったんだよ。そのうち、何となく結婚しようかってことになって。

山田：はっは、何となくか。それで、その際どちらの両親も賛成してくれたの？何と言っても国際結婚だから。



♯　解説　♭

　「～際／～節」のどちらも「とき」を表します。「～際」は「～の時を利用して～する」という積極的な表現で、後件では意志表現が使われます。ですから、偶発的な出来事や自然現象など無意志現象に使うと不自然になります。この場合は「～折」（→文型023）が自然になります。

　　　　　　　　先生に会うつもりだ。＜・際／？折り＞

　　上京のとき　雨に降られた。　　　＜？際／・ 折り＞

　　　　　　　　偶然先生に会った。　＜？際／・ 折り＞

　「～節」は意味用法とも「～折」と共通しますが、手紙や電話などのていねいな会話で多く使われ、敬語と結びつくことが多いのが特徴です。ただし、文末で「～なさい／～なければならない／～だろう」などの強い意志表現や推量表現が使えません。



§　例文　§

１．この際だから、言いたいことは言わせてもらうよ。

２．非常の際には、このドアから避難してください。

３．何か困った際は、いつでも連絡してください。

４．その節はいろいろお世話になりまして、本当にありがとうございました。

５．お暇な節は、是非お越しくださいませ。



★　例題　★

1)　先日お会いした（際／際／間際）に御相談した件でございますが、（なにとぞ／なにかと）よろしく御検討ください。御返事をお待ち（して／になって）おります。

2)　貴国を（訪問する→　　　　）節、何かと私どものためにお骨折りくださり、誠に感謝（　）堪えません。一同を代表して心からお礼を（述べて→　　　　　　）いただきます。



(^^)前課の解答(^^)

1)　によって（→文型348）／明るみ／に（「～が明るみに出る」は慣用）

2)　使いたくはない／甘さ／選ば（～ず→文型121）



## 099 ＊～最中に／＊～最中は／＊～最中だ



名詞：　　　　の　　　　　　＋　　最中に

動詞：～ている／～ていた　　　　　最中は

(注：形容詞「忙しい」につく例もある）



♪　会話　♪

山田：今は決算期で忙しい最中なので、日を改めてお電話ください。それではまた！

李　：以前つき合っていた彼女からの電話だろ？冷たいこと言わずに、話だけでも聞いてやれよ。

山田：私用電話を仕事の最中にかけてこられると、往生するよ。それに、もう彼女とよりを戻す気はないし。



♯　解説　♭

　「～最中」は「ちょうど～ているところ」＜動作継続中＞を表します。しかし「最中」は行為の最も重要なピーク時を表す語なので、例文１の「タバコを吸っているところ」を「～最中に」変えると不自然になりますし、例文２の「慌てているところ」ような行為ではなく心理状態を表すときは使えなくなります。その点、「～ところ」は動作動詞でも、感情・感覚・心理を表す動詞でも広く使うことができます。

　この「～最中」と類義語に「～中」（→文型188）がありますが、名詞との接続の形が違いますから、注意しましょう。

　食事の最中　ー　食事中

　電話の最中　ー　電話中



§　例文　§

１．トイレでタバコを吸っているところ（×最中）を教師に見つかり、停学処分にされた。

２．引っ越しの真っ最中に雨が降り出し、慌てているところ（×最中）です。

３．みんなが食事をしている最中を、突然、大地震が襲った。

４．今、容疑者の取り調べをしている最中だが、なかなか口を割らない。

５．人が話している最中に、横から口を挟まないでください。



★　例題　★

1)　山で道（で／に）（迷ったから／迷って）、途方に暮れていた（最中／ところ）に、地元の人が通りかかった。

2)　今は締め切り（　）前にして、原稿を（書く→　　　　）最中だから、その話は今度（　）してくれ。



(^^)前課の解答(^^)

1)　際（さい）／なにとぞ（副詞：依頼）／して（謙譲→文型019）

2)　訪問した／に（→文型323）／述べさせ（→文型102）


continue at
http://viethuong.web.fc2.com/MONDAI/100.html




